### ISSUE TITLE
AddDefaultIdentity shows up twice 

### ISSUE THREAD

**Issue by HaoK** [dotnet/Scaffolding#1275]
Note: This is likely due to AddDefaultIdentity appearing in both Startup and IdentityHostingStartup

From: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/942335

REPRO STEPS
The following steps are form Scaffold identity into an MVC project with authorization to create a new user context.
1. File > New Project > ASP.NET Core Web Application > .Net Core ~ ASP.NET Core 2.2 >Web Application (Model - View Controller) with IndAuth> Create.
2. Right-click project > Add > New Scaffolded Item.
3. From the left pane of the Add Scaffold dialog, select Identity > ADD.
4, In the ADD Identity dialog, Select existing layout page: ~/Views/Shared/_Layout.cshtml
5. Select the + button to create a new Data context class, select add.
6. Delete the Pages/Shared folder and the files in that folder.
7. F5

Note: 
1. If you use your existing data context do below step on step 5, the issue will not repro.
Select the following files to override:
Account/Register
Account/Manage/Index
Select your data context class.
Select ADD.
2. With NoAuth project, creating a new Data context works fine.

**Comment by vijayrkn** [comment]
@deepchoudhery - This is the one that is "Fixed pending release" correct?

**Comment by deepchoudhery** [comment]
No, it's a different issue. This is not VS related.

**Comment by deepchoudhery** [comment]
@HaoK For this issue, we could either ask users to edit Startup.cs to remove previous identity setup code in the ScaffoldingReadme.txt. Or we remove it from Startup.cs when identity is being setup. 

Currently, IdentityHostingStartup does not overwrite the existing file, so even when a new data context is selected, the content of IdentityHostingStartup remains unchanged.

**Comment by HaoK** [comment]
Maybe just update the readme?

**Comment by deepchoudhery** [comment]
Yes, that's what I was thinking. 

@Rick-Anderson, In the current identity scaffolding readme, we point to https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.1&tabs=visual-studio.

Can we add a small blurb like the following:

"If scaffolding Identity with a new data context into a project with existing individual accounts, remove the following references in Startup.ConfigureServices :
- AddDefaultIdentity - older identity reference.
- AddDbContext - references to older db context.

The newer references can be found found in Areas/Identity/IdentityHostingStartup.cs"

Let me know what you think of it

**Comment by deepchoudhery** [comment]
Looks good ty.

**Comment by Rick-Anderson** [comment]
@HaoK  you can close this and  https://devdiv.visualstudio.com/DevDiv/_workitems/edit/942335 
Fixed in dotnet/AspNetCore.Docs#18061

**Comment by HaoK** [comment]
Done, thanks @Rick-Anderson and @deepchoudhery
