### ISSUE TITLE
Update identity scaffolder to support excluding files

### ISSUE THREAD

**Issue by danroth27** [dotnet/Scaffolding#1296]
In some cases you may want to run the Identity scaffolder to generate all files except one or two. For example, a Blazor Server app with Identity has a customized LogOut.cshtml page that is required for logout to work. So if you want to scaffold in identity you need to scaffold in everything *except* LogOut.cshtml. You can do this with the current inclusion list support, but it's pretty verbose and clunky.

**Comment by deepchoudhery** [comment]
Fixed as part of #1324. Will go out in 5.0.0-preview4 and 3.1.3 servicing update.
