### ISSUE TITLE
Error: There was an error running the selected code generator: 'Scaffolding does not support project target framework '5.0''

### ISSUE THREAD

**Issue by donhuvy** [dotnet/Scaffolding#1317]
## Actual behavior:

![scaffolding_01](https://user-images.githubusercontent.com/1328316/79361442-80f72780-7f6f-11ea-89f7-8c277199c5ef.png)

![scaffolding_02](https://user-images.githubusercontent.com/1328316/79361468-87859f00-7f6f-11ea-9a1b-70977ff5d733.png)

**Comment by vijayrkn** [comment]
@donhuvy Thank you for reporting this issue. We are adding support for scaffolding ASP.NET 5.0 application in 16.6 Preview 4 / 5.0 Preview3
