### ISSUE TITLE
[Blazor] RegisterConfirmationModel missing using 

### ISSUE THREAD

**Issue by douglassimaodev** [dotnet/Scaffolding#1322]
Blazor webassembly

After Scaffolding Identity, it is missing: using Microsoft.AspNetCore.Identity;  in RegisterConfirmationModel

**Comment by vijayrkn** [comment]
@blowdart - The content for scaffolding templates is still maintained by @HaoK . From the issue description it looks like this template needs an update 

https://github.com/dotnet/Scaffolding/blob/0c12489f42293594f8c71f161ab93a74b25d6d2a/src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.RegisterConfirmation.cs.cshtml

Assigning it to @HaoK

**Comment by HaoK** [comment]
This was already fixed via https://github.com/dotnet/Scaffolding/pull/1284
