### ISSUE TITLE
Prevent Nuget Package From Automatically Updating When Scaffolding

### ISSUE THREAD

**Issue by davrob01** [dotnet/Scaffolding#1343]
## Steps to reproduce:

When Microsoft.VisualStudio.Web.CodeGeneration.Design 3.1.2 is installed, add a new view or controller via Visual Studio UI (uses the scaffolding engine).

## Expected behavior:

Visual Studio uses the  Microsoft.VisualStudio.Web.CodeGeneration.Design 3.1.2 package currently installed.

## Actual behavior:

Visual Studio automatically updates the package  Microsoft.VisualStudio.Web.CodeGeneration.Design 3.1.2 to version 3.1.3

### Package version of Microsoft.VisualStudio.Web.CodeGeneration.Design - this may be added to your project by scaffolding: 3.1.2

Hello,

Is there a way for me to have control over whether or not the nuget package Microsoft.VisualStudio.Web.CodeGeneration.Design is automatically updated (if there is an update available) when I scaffold an item? I noticed that it automatically updated today when scaffolding a new item.

My concern is that an update could - potentially - cause my custom templates to no longer get used because of MAYBE a change to how they are expected to be stored - physical directory. I would like to keep all my projects using the same version of Microsoft.VisualStudio.Web.CodeGeneration.Design for the sake of consistency if possible. This way I dont have to worry about any breaking changes. And I can update if I want to, explicitly.

Also how does Visual Studio know to update this package? Does it update whenever there is a new version or does it just try to keep the version numbers in sync with Microsoft.AspNetCore.App version?

Other Notes: I am using custom view templates at the project level in Templates\ViewGenerator_Versioned\Bootstrap3\

**Comment by deepchoudhery** [comment]
We try to keep them up to date since a lot users would not manually update the packages from nuget package manager for our bug fixes. However, we tend not to make any breaking changes in the minor updates so the difference between 3.1.2 and 3.1.3 is minor(mostly template updates). If anything breaks definitely open an issue here and I will help you out. 

VS knows the latest version for a particular tfm over the air and forces those versions. 

For the future updates, I'll try to think of a better update system that can avoid such a case.

**Comment by gtigtoxt** [comment]
Pra mim não funciona de forma nenhuma, já tentei todas as soluções mas o scaffolding não funciona.
![bug_vs2022](https://user-images.githubusercontent.com/36681443/191318507-99963c28-cfb3-4422-bed7-bae4d3497094.png)

**Comment by deepchoudhery** [comment]
hi,
2 workarounds for this : 
- you can use `dotnet-aspnet-codegenerator` from the commandline after setting all your preferred package versions. you can find the command being executed from the output window.
- you can use the new `dotnet-scaffold` tool. Blog[ here](https://devblogs.microsoft.com/dotnet/introducing-dotnet-scaffold/).

Let me know if you have more questions, closing for now.
