### ISSUE TITLE
Identity scaffolder: No class="btn btn-default" in TwoFactorAuthentication.cshtml

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/Scaffolding#1350]
ASP.NET Core 3.1
The [TwoFactorAuthentication.cshtml](https://github.com/dotnet/Scaffolding/blob/master/src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Manage/Account.Manage.TwoFactorAuthentication.cshtml) template uses `class="btn btn-default"` which can't be found by default. No other template uses this class. Selecting  2FA  yields a link styled like text. This bug is only found when you scaffold Identity, it's not found in the Identity RCL (Razor Class Libarary).

To repo:

```
dotnet new webapp -au Individual -uld -o RPauth
cd RPauth
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design
dotnet aspnet-codegenerator identity -dc RPauth.Data.ApplicationDbContext 
```

Register > sign in > select login > select 2FA

To fix, replace ` class="btn btn-default"` with `class="btn btn-primary"` like the rest of the templates.

cc @HaoK 
I could probably PR this with some help from @deepchoudhery

**Comment by deepchoudhery** [comment]
has been fixed (bootstrap 5 and dotnet-scaffold templates), closing.
