### ISSUE TITLE
Import 'Microsoft.WebTools.Scaffolding.Core.ScaffolderFactory.FactoryConfigEvaluator' could not be satisfied.

### ISSUE THREAD

**Issue by BrunoBlanes** [dotnet/Scaffolding#1364]
## Steps to reproduce:
Follow [this tutorial](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.1&tabs=visual-studio#scaffold-identity-into-a-blazor-server-project-with-authorization) on scaffolding Identity for a Blazor application.

## Expected behavior:
New pages be generated for customization.

## Actual behavior:
![image](https://user-images.githubusercontent.com/28227097/86406580-c3382700-bc89-11ea-9a86-8626fa9877f1.png)

### Target framework(s):
NET 5 Preview 6
Blazor WASM
Visual Studio Version 16.7.0 Preview 3.1

### Package version of Microsoft.AspNetCore.App or Microsoft.AspNetCore.All (if applicable):
Not?

### Package version of Microsoft.VisualStudio.Web.CodeGeneration.Design - this may be added to your project by scaffolding:
Doesn't get done.

Read the note (sorry for ignoring it), opening this issue on request from @deepchoudhery .

**Comment by Rick-Anderson** [comment]
I reported it [here for Visual Studio](https://developercommunity.visualstudio.com/content/problem/1098785/scaffolding-error-import-microsoftwebtoolsscaffold.html)

I reproduced the problem creating a new Razor Pages web app.
[Internal ticket](https://dev.azure.com/devdiv/DevDiv/_search?type=workitem&lp=workitems-Project&text=DeveloperCommunityId:1098785&filters=Projects{DevDiv}&_a=search)

**Comment by deepchoudhery** [comment]
@BrunoBlanes 
I need more information to help. There is a .err file in C:\Users\%USER%\AppData\Local\Microsoft\VisualStudio\16.0_XYZ\MEFCacheBackup where 16.0_XYZ is some alphanumeric code corresponding your specific VS install. I personally have not been able to reproduce this issue but having that file will help. If you have multiple VS install, feel free to send multiple error files. 

Let me know if you have any questions.

**Comment by BrunoBlanes** [comment]
The file I have is from February.  I don't think there would be anything related to this issue specifically since I didn't encounter it back then. Do you still want it?

**Comment by deepchoudhery** [comment]
Hmm and you have no other versions of VS installed?

**Comment by deepchoudhery** [comment]
I'll still take whatever file you have.

**Comment by deepchoudhery** [comment]
Check the ComponentModelCache folder after 16.0_XYZ actually. That should have a newer file. Editing the original comment,

**Comment by BrunoBlanes** [comment]
Yes, in fact there is. I changed the extension so I could upload as a file.

[Microsoft.VisualStudio.Default.log](https://github.com/dotnet/Scaffolding/files/4881259/Microsoft.VisualStudio.Default.log)

**Comment by deepchoudhery** [comment]
I would you like to repro the error and then get this file again. Every launch refreshes it(probably why I don't see anything related in it). Thanks a lot.

**Comment by Rick-Anderson** [comment]
The path is `C:\Users\%USERNAME%\AppData\Local\Microsoft\VisualStudio\`
I put my .err file at https://www.dropbox.com/s/ph4izsgtb1hf6jt/Microsoft.VisualStudio.Default.err?dl=0

**Comment by BrunoBlanes** [comment]
Relaunching Visual Studio didn't update it, so I moved all files from that folder to a temporary one, restarted the computer and then restarted VS so it could recreate those files. Here is the .err file:

[Microsoft.VisualStudio.Default.log](https://github.com/dotnet/Scaffolding/files/4881327/Microsoft.VisualStudio.Default.log)

**Comment by BrunoBlanes** [comment]
I should point out that the file was created before I open the project and it wasn't updated when I recreated the error.

**Comment by deepchoudhery** [comment]
Hi,
I have a couple things I would like you to try. Try just repairing your VS install through the Visual Studio installer.
Also if you could side install the same version of VS and see if the issue is still there. I'm leaning towards a faulty install but not sure yet.
Thanks a lot.

**Comment by BrunoBlanes** [comment]
Ok, will do and let you know.

**Comment by BrunoBlanes** [comment]
So, after a repair it hanged for a few seconds and then it reproduced the same error. After that it doesn't hang anymore, just straight up shows the pop-up message.
About side loading, what do you recommend? Like on a VM or a version other then VS Community?

**Comment by deepchoudhery** [comment]
Hmmm ok. I would recommend download the exact same preview version (enterprise/professional/community) and install it at a different path. If the installer does not let you easily, use https://docs.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples?view=vs-2019 (--installPath) to do it fairly easily. 
Did the error happen after an update or from a fresh install? We're figuring it something faulty in the update.

Thanks a lot,
Deep

**Comment by deepchoudhery** [comment]
Also, @BrunoBlanes do you have other versions of Visual Studio installed?

**Comment by BrunoBlanes** [comment]
I don't know when it started because I never used this feature before this version and I only have Visual Studio Version 16.7.0 Preview 3.1 Community installed. I will try to side install it as instructed and will let you know.

**Comment by BrunoBlanes** [comment]
Yep, yah nailed it. I did a command line install and selected a folder on my Downloads as the path. It worked like a charm.

Also, this looks super cool, though I wonder why is it even possible. 
![image](https://user-images.githubusercontent.com/28227097/86988290-4b2c9e00-c16e-11ea-8af5-41e3762d4b96.png)


I guess I will be doing a clean install of Visual Studio to fix the bug on the version installed to the default directory... Is there a "Clean Install tool" I can use?

**Comment by BrunoBlanes** [comment]
I did find a little bit of a bug though, or at least a point for improvement:
![image](https://user-images.githubusercontent.com/28227097/86992151-3e607800-c177-11ea-9f1b-6e6777cf8e10.png)

If you select to create a new data context class to use an existing user class and then change back to an existing data context, the user class field is disabled but not emptied, meaning that I get the following error:
![image](https://user-images.githubusercontent.com/28227097/86992260-7962ab80-c177-11ea-8945-192824c2983e.png)

Of course all I had to do was restart the process and not change my mind mid-way through, but I still think this is an easy and welcome fix. Where is the proper place to post this suggestion?

**Comment by Rick-Anderson** [comment]
> Of course all I had to do was restart the process and not change my mind mid-way through, but I still think this is an easy and welcome fix. Where is the proper place to post this suggestion?

Seems not worth fixing in lieu of all the other things we've got scheduled., You can open a new issue [here](https://github.com/dotnet/Scaffolding/issues)

**Comment by deepchoudhery** [comment]
Hey @BrunoBlanes. I have a workaround for your older vs instance if you would prefer to fix it.
I will need you to do the following:

1. Delete %ProgramData%\Microsoft\VisualStudio\Packages\Microsoft.VisualStudio.Web.Scaffolding,version=16.6.XXX.XXXX,chip=neutral,language=en-US.​
  _Note_ : the package you delete here should have "chip=..." and "language=...". It might be a different version but it should have 
  it since its the thing causing the problem.
  also %ProgramData% usually is C:\ProgramData​

2. Launch VS installer and select Repair.

Let me know if that works.

**Comment by BrunoBlanes** [comment]
Thanks @deepchoudhery that fixed it. I also did open a new issue for that little bug as instructed by @Rick-Anderson just in case you guys find the time.

**Comment by deepchoudhery** [comment]
Ok I'll look at that in the 16.8 Preview timeline. Thanks.

**Comment by donhuvy** [comment]
disadvantage, file download for repairing is too large (4.8 GB)

![image](https://user-images.githubusercontent.com/1328316/90757837-54319300-e308-11ea-94c2-63433caa57c6.png)

**Comment by donhuvy** [comment]
I post a question and an answer at here https://stackoverflow.com/questions/63502800/import-microsoft-webtools-scaffolding-core-scaffolderfactory-factoryconfigevalu/63502867#63502867

**Comment by TheDevTwister** [comment]
if any one having Syncfusion in their system then also this issue come up. so disable it if you are not using it else you can take help from below URL

https://forums.asp.net/t/2169754.aspx?Adding+new+scaffolded+item
