### ISSUE TITLE
Add bootstrap modal Popup

### ISSUE THREAD

**Issue by davidbuckleyni** [dotnet/Scaffolding#1369]
It would be good as a developer for us to be able to tick a tick box to say use bootstrap a version number would appear with 3/4 or 5. After selecting this if we could have an option to select to use the forms in views inline or as a Popup.

This would save allot of code customisations. 

Is there any documentation on how to run a customer scaffolder fork if we do the changes there first.

**Comment by deepchoudhery** [comment]
There is a [bootstrapVersion ](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/tools/dotnet-aspnet-codegenerator?view=aspnetcore-3.1)commandline parameter for identity, razor pages, views. You may use the command line tool when in the project directory. Were you thinking of a bootstrap selector in VS?
