### ISSUE TITLE
Visual studio 16.7.0 adding new scaffolded item

### ISSUE THREAD

**Issue by bernardj1905** [dotnet/Scaffolding#1386]
caused me this error:

![image](https://user-images.githubusercontent.com/69394805/89714087-80f6b980-d99c-11ea-854a-d25a81720d1c.png)

This is the csproj file:

![image](https://user-images.githubusercontent.com/69394805/89714152-01b5b580-d99d-11ea-9d18-16db198d0e97.png)

Any solution for this?
Thanks!

**Comment by deepchoudhery** [comment]
What VS version are you on?

**Comment by bernardj1905** [comment]
I'm using the version 16.7, and when I disabled syncfusion extensions, adding the new scaffolding item is working.

**Comment by deepchoudhery** [comment]
Hmm interesting. I'll try the scenario with that extension installed. I'll let you know soon.

**Comment by bernardj1905** [comment]
Thanks!

**Comment by mtu305** [comment]
is there any new?

**Comment by deepchoudhery** [comment]
@mtu305 are you running into this issue? We had similar issues that got resolved by https://github.com/dotnet/Scaffolding/issues/1364#issuecomment-656289811.

Let me know if that helps. Also what version are you on? There should be a newer version available.

**Comment by mtu305** [comment]
my issue seem not fit with this.

**Comment by mtu305** [comment]
my issue here: [https://developercommunity.visualstudio.com/t/In-VS-2019-can-not-avaiable-the-custom/850618](url)
but it is close without solution

**Comment by deepchoudhery** [comment]
Hi, 
A VS repair will fix this issue. Also try the new dotnet-scaffold commandline tool. Blog [here](https://devblogs.microsoft.com/dotnet/introducing-dotnet-scaffold/). Closing for now.
