### ISSUE TITLE
Error With "aspnet-codegenerator identity" - Identity Scaffolder

### ISSUE THREAD

**Issue by glenn2223** [dotnet/Scaffolding#1410]
## Steps to reproduce:
1) Follow this instruction: [Create A Razor Web App](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-3.1&tabs=netcore-cli#create-a-razor-web-app)
2) Then follow this instruction: [Run The Identity Scaffolder](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-3.1&tabs=netcore-cli#run-the-identity-scaffolder). However I ran it without the files or user class parameters; so just `dotnet aspnet-codegenerator identity`

## Expected behavior:
To generate the appropriate files

## Actual behavior:
Getting an error message attached and copied below. However, it's a fresh project with the required NuGet package. I tried 3.1.4 and 5.0.0-preview.8.20419.1 (I have 5.0.0-preview8 SDK installed)

````POWERSHELL
PS C:\Users\graphite.rack\WebApp1> dotnet aspnet-codegenerator identity
[Trace]: Command Line: identity
Building project ...
Scaffolding failed.
Add Microsoft.VisualStudio.Web.CodeGeneration.Design package to the project as a NuGet package reference.
[Trace]:    at Microsoft.VisualStudio.Web.CodeGeneration.Tools.Program.CreateDipatchCommand(IProjectContext context, String[] args, String buildBasePath, String configuration, NuGetFramework frameworkToUse, ScaffoldingServer server) in /_/src/dotnet-aspnet-codegenerator/Program.cs:line 255
   at Microsoft.VisualStudio.Web.CodeGeneration.Tools.Program.BuildAndDispatchDependencyCommand(String[] args, String projectPath, String buildBasePath, String configuration, Boolean noBuild, ILogger logger) in /_/src/dotnet-aspnet-codegenerator/Program.cs:line 190
   at Microsoft.VisualStudio.Web.CodeGeneration.Tools.Program.<>c__DisplayClass19_0.<Execute>b__0() in /_/src/dotnet-aspnet-codegenerator/Program.cs:line 131
RunTime 00:00:06.71
````

![Example](https://user-images.githubusercontent.com/33450392/92890811-5ec6e000-f40f-11ea-9944-99ef69ee2b26.png)

### Target framework(s):
.NET 5-preview8

### Package version of Microsoft.AspNetCore.App or Microsoft.AspNetCore.All (if applicable):
N/A, my target `Microsoft.NET.Sdk.Web` SDK implicitly references the `Microsoft.AspNetCore.App` framework.

### Package version of Microsoft.VisualStudio.Web.CodeGeneration.Design - this may be added to your project by scaffolding:
Tried both 3.1.4 and 5.0.0-preview.8.20419.1

**Comment by deepchoudhery** [comment]
The issue you state above is a known issue with the 5.0.0-Preview 8 sdk. There will be an update for 5.0 sdk soon. You may use the 3.1.4xx sdk or 5.0-Preview7. We have been having a fair amount of issues in the preview packages which will be ironed out soon.

**Comment by deepchoudhery** [comment]
Should be fixed with the latest stable release updates.
