### ISSUE TITLE
.NET 5 RC: Project \obj\project.assets.json' doesn't have a target for 'net50'. 

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/Scaffolding#1419]
Scaffolding works perfect from VS, only the CLI fails

## SOLVED

```
dotnet tool uninstall --global dotnet-ef
Tool 'dotnet-ef' (version '3.1.7') was successfully uninstalled.

dotnet tool install --global dotnet-ef --version 5.0.0-*

```

## Steps to reproduce:

```
dotnet new webapp -o ContosoUniversity
cd ContosoUniversity
```

Add the following `Student` model:

```
public class Student
{
    public int ID { get; set; }
    public string LastName { get; set; }
    public string FirstMidName { get; set; }
}
```

Run the following .NET Core CLI commands to install required NuGet packages:
```
dotnet tool install --global dotnet-aspnet-codegenerator --version 5.0.0-*
dotnet add package Microsoft.EntityFrameworkCore.SQLite -v 5.0.0-*
dotnet add package Microsoft.EntityFrameworkCore.SqlServer -v 5.0.0-*
dotnet add package Microsoft.EntityFrameworkCore.Design -v 5.0.0-*
dotnet add package Microsoft.EntityFrameworkCore.Tools -v 5.0.0-*
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design -v 5.0.0-*
dotnet add package Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore -v 5.0.0-*
```
Scaffold command

`dotnet aspnet-codegenerator razorpage -m Student -dc ContosoUniversity.Data.SchoolContext -udl -outDir Pages\Students --referenceScriptLibraries`

## Expected behavior:

Scaffold Student

## Actual behavior:
 error NETSDK1005: Assets file 'c:\tmp\x\ContosoUniversity\obj\project.assets.json' doesn't have a target for 'net50'. Ensure that restore has run and that you have included 'net50' in the TargetFrameworks for your project. [c:\tmp\x\ContosoUniversity\ContosoUniversity.csproj]

See [project.assets.json](https://github.com/Rick-Anderson/ToDoDTO/blob/master/project.assets.json)

Build FAILED.

C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(241,5): error NETSDK1005: Assets file 'c:\tmp\x\ContosoUniversity\obj\project.assets.json' doesn't have a target for 'net50'. Ensure that restore has run and that you have included 'net50' in the TargetFrameworks for your project. [c:\tmp\x\ContosoUniversity\ContosoUniversity.csproj]
    0 Warning(s)
    1 Error(s)

## Environment
Windows 10, fully patched 
5.0.100-rc.1.20452.10

**Comment by Jason5Lee** [comment]
I have the same problem. How'd you solve it?

**Comment by en1tan** [comment]
Facing same issue
Ubuntu 18.04

**Comment by asanobm** [comment]
<img width="1341" alt="スクリーンショット 2020-12-07 11 40 08" src="https://user-images.githubusercontent.com/38549104/101303253-f7d78c80-3880-11eb-8beb-7523dff08136.png">

Same issue OSX

**Comment by asanobm** [comment]
Hi @en1tan 

I had the same issue.

I updated `dotnet-aspnet-codegenerator` and it worked fine.

[please check document](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/tools/dotnet-aspnet-codegenerator?view=aspnetcore-5.0)

<img width="1341" alt="スクリーンショット 2020-12-07 11 59 24" src="https://user-images.githubusercontent.com/38549104/101304475-a7adf980-3883-11eb-854d-b0f62e7b022c.png">
