### ISSUE TITLE
RazorPageGeneratorTemplateModel2' does not contain a definition for 'ViewDataTypeShortName'

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/Scaffolding#1432]
Moved from https://github.com/dotnet/AspNetCore.Docs/issues/20226 by @paolovalladolid

I ran this command:

dotnet aspnet-codegenerator razorpage Edit Edit -outDir Pages\Restaurants

I got this error:

Building project ...
Finding the generator 'razorpage'...
Running the generator 'razorpage'...
'Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Razor.RazorPageGeneratorTemplateModel2' does not contain a definition for 'ViewDataTypeShortName'
at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.b__6_0()
at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:05.23

I also ran this command and got the same stack trace:
dotnet aspnet-codegenerator razorpage RestaurantEdit Edit -outDir Pages\Restaurants

**Comment by deepchoudhery** [comment]
I believe you need the model class on which the Edit template will be applied on.  I'll run some tests and get back to you. Definitely need better error messages.

**Comment by deepchoudhery** [comment]
Fixed with the new dotnet-scaffold tool. Blog [here](https://devblogs.microsoft.com/dotnet/introducing-dotnet-scaffold/)
