### ISSUE TITLE
Area Scaffolding generates empty folders

### ISSUE THREAD

**Issue by felipeklassmatt** [dotnet/Scaffolding#1434]
## Steps to reproduce:

dotnet new mvc -n m1 && cd m1
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design

dotnet tool update -g dotnet-aspnet-codegenerator
dotnet aspnet-codegenerator area Admin

## Expected behavior:
Files within the Area Admin folder.
## Actual behavior:
Only empty folders

**Comment by deepchoudhery** [comment]
Hmm what files are you expecting under the Areas folders? We expect these folders to be empty and to only provide folder structure for views and Razor Pages (with our naming conventions).

**Comment by felipeklassmatt** [comment]
I may be confusing with Identity scaffolding, but shouldn't it have a HostingStartup class, controller and context files?

**Comment by deepchoudhery** [comment]
You are confusing it with identity yes. Area just provides folder structure. Gonna close this for now but feel free to ask questions here.
