### ISSUE TITLE
Identity Scaffolding on Ubuntu 20.04 using incorrect file paths dotnet 5

### ISSUE THREAD

**Issue by mmousa8189** [dotnet/Scaffolding#1471]
Output of `dotnet --info`:

```
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.101/

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  3.1.404 [/usr/share/dotnet/sdk]
  5.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

## Steps to reproduce:

1. Install the code generator: dotnet tool install -g dotnet-aspnet-codegenerator
2. Create a project to scaffold into dotnet new webapp --auth Individual -o WebApp1
3. cd into the new project directory
4. Install Microsoft.VisualStudio.Web.CodeGeneration.Design
6. Build the project to make sure everything works (build OK)
7. run scaffold : 
`dotnet aspnet-codegenerator identity -dc WebApp1.Data.ApplicationDbContext --files "Account.Register;Account.Login;Account.Logout;Account.RegisterConfirmation"
`
## Expected behavior:
All Identity.UI Razor Pages are scaffolded into the project

## Actual behavior:
A fatal error indicating a file was not found:

`Account.RegisterConfirmation"
Building project ...
Finding the generator 'identity'...
Running the generator 'identity'...
A file matching the name Account.Register.cs.cshtml was not found within any of the folders: 
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:09.87`

### Target framework(s):
**net5.0**
### Package version of Microsoft.AspNetCore.App or Microsoft.AspNetCore.All (if applicable):
**5.0.1**
### Package version of Microsoft.VisualStudio.Web.CodeGeneration.Design - this may be added to your project by scaffolding:
**5.0.1**

**Comment by mmousa8189** [comment]
I found an issue related to my issue 

[https://github.com/dotnet/aspnetcore/issues/26524](https://github.com/dotnet/aspnetcore/issues/26524)

**Comment by jahnog** [comment]
It seems to work with Net Sdk 5.0.102

**Comment by guustysebie** [comment]
updated sdk to  5.0.102 still doesn't work

> 
> NET SDK (reflecting any global.json):
>  Version:   5.0.102
>  Commit:    71365b4d42
> 
> Runtime Environment:
>  OS Name:     ubuntu
>  OS Version:  20.04
>  OS Platform: Linux
>  RID:         ubuntu.20.04-x64
>  Base Path:   /usr/share/dotnet/sdk/5.0.102/
> 
> Host (useful for support):
>   Version: 5.0.2
>   Commit:  cb5f173b96
> 
> .NET SDKs installed:
>   3.1.405 [/usr/share/dotnet/sdk]
>   5.0.102 [/usr/share/dotnet/sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 3.1.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 3.1.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
> 
> To install additional .NET runtimes or SDKs:
>   https://aka.ms/dotnet-download

**Comment by deepchoudhery** [comment]
@mmousa8189  @jahnog @guustysebie 
I have a fix for this issue out with a new 3.1.5 and 5.0.2 package out.  
Use dotnet tool update dotnet-aspnet-codegenerator -g --version 3.1.5/5.0.2 depending on if you are targeting .netcoreapp3.1 or net5.0.  I would like it if someone could confirm the fix before I close the issue. 

Apologize for the lengthy delay on this fix and appreciate all the feedback.

**Comment by rolambert** [comment]
> @mmousa8189  @jahnog @guustysebie 
> I have a fix for this issue out with a new 3.1.5 and 5.0.2 package out.  
> Use dotnet tool update dotnet-aspnet-codegenerator -g --version 3.1.5/5.0.2 depending on if you are targeting .netcoreapp3.1 or net5.0.  I would like it if someone could confirm the fix before I close the issue. 
> 
> Apologize for the lengthy delay on this fix and appreciate all the feedback.

Thanks! I will test this out and get back to you probably tomorrow.

**Comment by deepchoudhery** [comment]
Seems to work based on other feedback. Closing.

**Comment by rolambert** [comment]
Yes it worked for me, Thankyou!

**Comment by mmousa8189** [comment]
@rolambert  thanks Robert and I'm sorry the last 7 months I'm very busy on R&D Projects.
