### ISSUE TITLE
Microsoft.VisualStudio.Web.CodeGeneration.Design 5.0.3 nuget is missing

### ISSUE THREAD

**Issue by maxima120** [dotnet/Scaffolding#1510]
The highest version available from nuget.org is 5.0.2
Please publish 5.0.3. dotnet core 5.0.3 was released weeks ago.

**Comment by deepchoudhery** [comment]
We don't really need to match the versions with dotnet core. The 5.0.2 package should work with dotnet 5.0.3. 
We make updates when we really need to.
Closing.
