### ISSUE TITLE
how to build the project and install in visual studio 2019 replace default template

### ISSUE THREAD

**Issue by neozhu** [dotnet/Scaffolding#1527]
Where can I get the relevant documentation? 

I  want to generate controllers and views in my project according to my requirements

thank you

**Comment by vijayrkn** [comment]
You can find relevant documentation for scaffolding Razor pages in ASP.NET projects here : https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-6.0&tabs=visual-studio
