### ISSUE TITLE
code generator in .NET 3.1 does not work properly in Visual Studio.

### ISSUE THREAD

**Issue by Mr-Layegh** [dotnet/Scaffolding#1537]
Error :
{ There was an error running the selected code generator :
'Package restore failed. Rolling back package changes for [Project-Name] ' }

dotnet version : 3.1
Web.CodeGeneration.Design version : 3.1.5

Note : The problem is not due to the caching of Visual Studio or the build of the program.

**Comment by parysoid** [comment]
Same issue with .NET Core 3.1 and Web.CodeGeneration.Design 3.1.5

**Comment by Rick-Anderson** [comment]
You need matching packages in the project file. Roll them back until you have a  matching set and it works fine.
