### ISSUE TITLE
[Infrastructure] remove unnecessary network/graph calls.

### ISSUE THREAD

**Issue by deepchoudhery** [dotnet/Scaffolding#1560]
in MicrosoftIdentityPlatformApplicationManager.cs and maybe more

**Comment by jmprieur** [comment]
@deepchoudhery 
we might also want to discuss this one.

I'm not aware of any un-necessary network/graph calls. Which scenarios do you support? are you sure you considered all the scenarios?

Happy to chat / meet if that helps.
cc: @sayedihashimi

**Comment by deepchoudhery** [comment]
There are a couple I have introduced so nothing from what was already there. I'll tag you in the PR

**Comment by deepchoudhery** [comment]
Tool will be reworked, closing.
