### ISSUE TITLE
Support scaffolding using native Cosmos DB client

### ISSUE THREAD

**Issue by markjbrown** [dotnet/Scaffolding#1570]
The scaffolder does a great job creating controllers over models with DI for DBContext. I'd like to extend that such that it could work with the native Cosmos DB client. This would provide the same productivity benefits for users that would like to use Cosmos DB.

Same scaffolding but with a command line argument to scaffold using Cosmos DB.

**Comment by deepchoudhery** [comment]
Added since .NET 7, closing.
