### ISSUE TITLE
How to replace the default template when rebuild this project?

### ISSUE THREAD

**Issue by neozhu** [dotnet/Scaffolding#1575]
have anyone tell me?
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.3

**Comment by deepchoudhery** [comment]
What templates are you trying to replace? I'll have some details below:
- Default layout : _Layout.cshtml in Views/Pages folder for MVC/Razor Pages project.
- Most other templates live in src/Scaffolding/VS.Web.CG.Mvc/Templates
  - Api/Mvc/Empty controllers : ControllerGenerator
  - Identity : Identity
  - Razor Pages : RazorPageGenerator
  - Razor Views : ViewGenerator.

So edit whatever templates you need to edit, build and install using scripts\install-aspnet-codegenerator.cmd. 

Let me know if that helps,
Deep

**Comment by neozhu** [comment]
thank you for your information, I got it
