### ISSUE TITLE
Cannot create Controller through terminal

### ISSUE THREAD

**Issue by shirliv** [dotnet/Scaffolding#1576]
Hi,

I've read several threads with similar or same problems and tried the solutions in them but nothing works for me, so I'll write down my specific case:

I'm using Visual Studio Code on Windows.
My problem is that I'm unable to use the codegenerator tool to create a Controller.
I typed the following command in the CLI:

> dotnet aspnet-codegenerator controller -name MessageController -m Message -dc MessageDbContext --relativeFolderPath Controllers --useDefaultLayout --referenceScriptLibraries

And the response is:

> Building project ...
Finding the generator 'controller'...
No code generators found with the name 'controller'
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGeneratorsLocator.GetCodeGenerator(String codeGeneratorName)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:21.02

The sdks I have are (if I type dotnet --list-sdks):

> 3.1.409 [C:\Program Files\dotnet\sdk]
5.0.202 [C:\Program Files\dotnet\sdk]
5.0.203 [C:\Program Files\dotnet\sdk]

I have a global.json file I've created and its contents are as follows:

> {
  "sdk": {
    "version": "3.1.408"
  }
}

My .csproj is as follows:

``` <Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UserSecretsId>aspnet-MyApplication-SomeIDIReplaced</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <None Update="app.db" CopyToOutputDirectory="PreserveNewest" ExcludeFromSingleFile="true"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="3.1.14"/>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.1.14"/>
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.1.14"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.14"/>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.4"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.14"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0"/>
  </ItemGroup>
</Project>
```

This is my first time trying to use this tool. I did do the install command and it seems that it installed it successfully, but when I type the command:

> dotnet aspnet-codegenerator --help

I get:

```   Usage: aspnet-codegenerator [arguments] [options]

Arguments:
  generator  Name of the generator. Check available generators below.

Options:
  -p|--project             Path to .csproj file in the project.
  -n|--nuget-package-dir
  -c|--configuration       Configuration for the project (Possible values: Debug/ Release)
  -tfm|--target-framework  Target Framework to use. (Short folder name of the tfm. eg. net46)
  -b|--build-base-path
  --no-build

No code generators are available in this project. Please add the 'Microsoft.VisualStudio.Web.CodeGeneration.Design' NuGet package to the project.Add Microsoft.VisualStudio.Web.CodeGeneration.Design package to the project as a NuGet package reference.

RunTime 00:00:05.27

```
Which as you can see is already in the csproj...
Could you please direct me as to what seems to be the problem and how to solve it?
Thank you very much

**Comment by deepchoudhery** [comment]
Hi,
We had issues with 3.1.4/5.0.1 versions of the CodeGeneration.Design package with generators and templates not being found. 
Please update the package version to 3.1.5/5.0.2 depending on your project target framework. I would also recommend performing a `dotnet restore` after the update.

Let me know,
Deep
