### ISSUE TITLE
How do I install myself compiled dotnet-scaffold and dotnet-aspnet-codegenerator tools?

### ISSUE THREAD

**Issue by neozhu** [dotnet/Scaffolding#1581]
## Ask a question
How do I install myself compiled dotnet-scaffold and dotnet-aspnet-codegenerator tools?

Microsoft.VisualStudio.Web.CodeGeneration.Design/Microsoft.DotNet.MSIdentity version:
Target framework: (e.g. .NET 5.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by deepchoudhery** [comment]
The scripts folder (Scaffolding/scripts) has scripts for installation. If you don't want to use the script itself, you can see the `dotnet tool install ...` command in there used for installing.

**Comment by neozhu** [comment]
thanks @deepchoudhery
