### ISSUE TITLE
Scaffolding fails when used against a project that uses C# 9 top-level statements

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/Scaffolding#1583]
Attempting to use a scaffolder against an ASP.NET Core project that uses top-level statements (e.g. the empty web template in .NET 6) fails with an error, e.g. in Visual Studio:

```
---------------------------
Microsoft Visual Studio
---------------------------
Error

There was an error running the selected code generator:

'Value cannot be null. (Parameter 'programType')'
---------------------------
OK   
---------------------------
```

**Comment by deepchoudhery** [comment]
We have a scaffolding rework planned (not tracked yet) for having C# 8, 9 support.  Will update this with milestones when tracked.

**Comment by DamianEdwards** [comment]
@deepchoudhery any update on this?

**Comment by vijayrkn** [comment]
This is also fixed. Scaffolding works with the latest minimal API .NET 6.0 templates.
