### ISSUE TITLE
Warning When Installing Latest NuGet Package 6.0.0-preview.7.21412.2

### ISSUE THREAD

**Issue by Mike-E-angelo** [dotnet/Scaffolding#1619]
## File a bug

The following warning is generated when the latest `Microsoft.VisualStudio.Web.CodeGeneration` (`6.0.0-preview.7.21412.2`) is installed:

```
warning NU1603: Microsoft.VisualStudio.Web.CodeGeneration 6.0.0-preview.7.21412.2 depends on System.Collections.Immutable (>= 6.0.0-preview.7.21377.12) but System.Collections.Immutable 6.0.0-preview.7.21377.12 was not found. An approximate best match of System.Collections.Immutable 6.0.0-preview.7.21377.19 was resolved.
```

We were tracking down another warning with this issue: https://github.com/dotnet/aspnetcore/issues/35300

That seems to be addressed and this issue is now the only one that appears in my NuGet restore.

### Include your code

NA

### Include stack traces

NA

### Include provider and version information

Microsoft.VisualStudio.Web.CodeGeneration.Design/Microsoft.DotNet.MSIdentity version: `6.0.0-preview.7.21412.2`
Target framework: (e.g. .NET 5.0) `net6.0`
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019 16.3) Visual Studio 2022 Preview 3.0

**Comment by andwi** [comment]
Still get the same warning with rc 1.

warning NU1603: Microsoft.VisualStudio.Web.CodeGeneration 6.0.0-rc.1.21464.1 depends on System.Collections.Immutable (>= 6.0.0-preview.7.21377.12) but System.Collections.Immutable 6.0.0-preview.7.21377.12 was not found. An approximate best match of System.Collections.Immutable 6.0.0-preview.7.21377.19 was resolved.

**Comment by Rick-Anderson** [comment]
cc @tdykstra  @deepchoudhery  hopefully this will be fixed for RC2

**Comment by vijayrkn** [comment]
6.0.0 version of the scaffolding package should address this issue.
