### ISSUE TITLE
Package dotnet-aspnet-codegenerator 5.0.2 is not compatible with net5.0

### ISSUE THREAD

**Issue by zhangran075** [dotnet/Scaffolding#1630]
I am following the instruction on Microsoft Documentation for establish a new RazorPage project, but when I wanna install dotnet-aspnet-codegenerator 5.0.2 on Visual Studio no matter using global install or NuGet package, it replys: 
"
Restoring packages for .NETCoreApp,Version=v5.0...
Resolving conflicts for net5.0...
Checking compatibility of packages on net5.0.
Checking compatibility for RazorPagesMovie 1.0.0 with net5.0.
Checking compatibility for Newtonsoft.Json 13.0.1 with net5.0.
Checking compatibility for dotnet-aspnet-codegenerator 5.0.2 with net5.0.
Package dotnet-aspnet-codegenerator 5.0.2 is not compatible with net5.0 (.NETCoreApp,Version=v5.0). Package dotnet-aspnet-codegenerator 5.0.2 supports: net5.0 (.NETCoreApp,Version=v5.0) / any
Invalid project-package combination for dotnet-aspnet-codegenerator 5.0.2. DotnetToolReference project style can only contain references of the DotnetTool type 
Incompatible packages: 2
Package 'dotnet-aspnet-codegenerator 5.0.2' has a package type 'DotnetTool' that is not supported by project 'RazorPagesMovie'.
"
Which caused that I can not add a scaffolding.
Anyone know how to fix the problem?

**Comment by vijayrkn** [comment]
@zhangran075 - Can you please share the contents of your csproj? 

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="5.0.2" />
  </ItemGroup>

</Project>
```

It should look like this with your code generation package. After this, you should be able to install the global tool as specified in the documentation - https://docs.microsoft.com/en-us/aspnet/core/fundamentals/tools/dotnet-aspnet-codegenerator?view=aspnetcore-5.0

Please re-open if this doesn't fix the issue.
