### ISSUE TITLE
Please fix the Add | New Scaffolded Item

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/Scaffolding#1648]
## Issue

I have a brand new project. (Note that my Entities are in a separate project.)

In Solution Explorer, I right click on the *Areas/Identity* folder, select *Add*, and select *New Scaffolded Item*.

Next, I choose Identity and click *Add*.

![image](https://user-images.githubusercontent.com/3191331/134365739-822e073e-adfb-4b0d-a097-eae6135cc46b.png)

Next, I select the files I want to override and select my data context class.

![image](https://user-images.githubusercontent.com/3191331/134366010-561d58fc-da64-4f4d-9f08-2a921427e3f2.png)

So here I run into issues. The data context class looks right. But does it need the user class? This box is disabled. Can anyone tell me the purpose of the user class box and why it's disabled?

If I continue, I get the all too familiar, and completely useless message below.

![image](https://user-images.githubusercontent.com/3191331/134366494-1594f454-8b46-4179-a3da-03667d20ff7c.png)

Is there any way to get this working? Is there any way to produce an error message that would allow the user to diagnose and try to fix the issue?

## Issue is not New

The *Add | New Scaffolded Item* command has been broken for a long time and I've reported several variations of it.

But I go on to new projects and then run into this again.

### Include provider and version information

Microsoft.VisualStudio.Web.CodeGeneration.Design/Microsoft.DotNet.MSIdentity version: 5.0.2/?
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.11.3

**Comment by SoftCircuits** [comment]
If we can't add scaffolding, is there any way we could have a way to manually download the identity pages and copy them into our project?

**Comment by vijayrkn** [comment]
@SoftCircuits - Sorry to hear that you are running into this issue and for our tardy response. Visual Studio issues are mostly tracked on the Visual Studio side and the best way to report them would be through the developer community channel. Instructions here : https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019

For this specific issue, the userclass is not required. I just verified the scenario using a 5.0 app and it scaffolded the identity pages for me correctly.  

Here are the steps: 
1. Create a new ASP.NET Core Web App targeting .NET 5.0 
2. Select `Individual accounts` in the authentication options.
3. Right click -> Add scaffolded item
4. Select identity
5. Select DB context
6. Add

You should see the following pages scaffolded out & similar messages in the code generation log


![image](https://user-images.githubusercontent.com/3981619/140366484-3a6be8e4-1aea-4730-8ade-cfe43c5a3729.png)


Ensure that all your packages are up to date before running the scaffolder. 

If the above doesn't fix the issue, please re-open.
