### ISSUE TITLE
dotnet-aspnet-codegenerator: command not found

### ISSUE THREAD

**Issue by Ken-Sarowiwa** [dotnet/Scaffolding#1657]
## File a bug
i am trying to generate a scafolding to help me implement the CRUD operations for project i am doing but i end up getting an error saying. "dotnet-aspnet-codegenerator: command not found".

i am running the following command :  "dotnet-aspnet-codegenerator razorpage -m Movie -dc ASPNETCOREAPPContext -udl -outDir Pages/Movies --referenceScriptLibraries -sqlite"

i am using an ubuntu environment with visual studio code, my ubuntu vesrion is 20.04 focal

**Comment by vijayrkn** [comment]
@Ken-Sarowiwa - Can you confirm if you have already installed the tooling using the command? 

dotnet tool install -g dotnet-aspnet-codegenerator

Here is the doc with the details on how to install the tool : https://docs.microsoft.com/en-us/aspnet/core/fundamentals/tools/dotnet-aspnet-codegenerator?view=aspnetcore-5.0
