### ISSUE TITLE
Scaffolding - subsequent identity DbContext additions

### ISSUE THREAD

**Issue by deepchoudhery** [dotnet/Scaffolding#1666]
Add incremented connectionString variables in identity scenarios when subsequent DbContexts are added.
Issue described here - https://github.com/aspnet/AspNetCore-ManualTests/issues/928

**Comment by JeffW12345** [comment]
The link above doesn't work - I got a 404.

**Comment by deepchoudhery** [comment]
Not planning to fix, closing.
