### ISSUE TITLE
Identity defines --useSqLite instead of --useSqlite

### ISSUE THREAD

**Issue by serpent5** [dotnet/Scaffolding#1704]
The scaffolding for Identity uses a parameter of `--useSqLite` instead of `--useSqlite` (capital `L`): https://github.com/dotnet/Scaffolding/blob/main/src/Scaffolding/VS.Web.CG.Mvc/ParameterDefinitions/identity.json#L27.

However, the scaffolding for MVC etc uses `--useSqlite`: https://github.com/dotnet/Scaffolding/blob/main/src/Scaffolding/VS.Web.CG.Mvc/ParameterDefinitions/view.json#L61.

Should the Identity scaffolding be changed to match that of MVC?

**Comment by deepchoudhery** [comment]
switched to `--databaseProvider`, fixed. Closing.
