### ISSUE TITLE
A type with name ... does not exist

### ISSUE THREAD

**Issue by equirev73** [dotnet/Scaffolding#1705]
### Description

Hi. I am using Visual Studio 2022 with NET 6.0. I created a blazor wasm solution with three projects. Added a model on Shared project. Then when I try to add a controller to the server project using scaffolding I get an error message "Type does not exist".

In Server project, over "Controllers" folder > Add > Controller > API > Controller API with accions ...

### Configuration
Windows 10 Pro 64-bit.  Just installed. Visual Studio 2022 NET 6.0.
I7 3667U 8GB.

### Regression?

I tested with Visual Studio 2022 preview NET 6.0. Same error.
I tested with Visual Studio 2022 NET 5.0 and works well.

### Other information
![Slide1](https://user-images.githubusercontent.com/58412457/141992885-efaa552d-9fc2-4cf0-bbd3-be621dfe0b68.jpg)

Thanks for any help you can provide!.

**Comment by LouisMilesRH** [comment]
Exactly the same problem for me!

**Comment by Rick-Anderson** [comment]
> If the model is in the shared project then it doesn't work.

I don't think scaffolding support shared projects. You'll have to temporarily copy the model to scaffold.

**Comment by borrmann** [comment]
same problem here

**Comment by bardkalbakk** [comment]
Duplicate of https://github.com/dotnet/Scaffolding/issues/1702

**Comment by deepchoudhery** [comment]
Issue fixed in the new [6.0.1](https://www.nuget.org/packages/Microsoft.VisualStudio.Web.CodeGeneration.Design/) package. Reopen the issue if it persists with the new package.

Thanks,
Deep

**Comment by deepchoudhery** [comment]
Issue fixed in the new [6.0.1](https://www.nuget.org/packages/Microsoft.VisualStudio.Web.CodeGeneration.Design/) package. Reopen the issue if it persists with the new package.

Thanks,
Deep
