### ISSUE TITLE
.NET 6 scaffolder timing bug with Microsoft.VisualStudio.Web.CodeGeneration.Design

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/Scaffolding#1710]
Currently when you scaffold anything you get an error that you need to install `Microsoft.VisualStudio.Web.CodeGeneration.Design`.

The scaffolder should add that. It adds other packages.

To repo:
* Run the scaffolder. For example, follow any of my tutorials such as
  * [Intro to RP](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-6.0&tabs=visual-studio#scaffold-the-movie-model)
  * [Intro to MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-6.0&tabs=visual-studio#add-nuget-packages)
  * [Scaffold Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-6.0&tabs=visual-studio)
  
***UPDATE***: @guardrex  noticed that invoking the scaffolder does add 
```
<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.0" />
```
So running it the 2nd time works.  So it looks like a timing issue.

**Comment by guardrex** [comment]
I even had a Blazor Server app this morning where the timing was good. There was no error about the package. Scaffolding took me from the **New Scaffolded Item** dialog directly to the **Add Identity** dialog. When I tried this afternoon to repro this morning's good behavior, a new Blazor Server app 💥 with the error ... *but added the package* ... a second scaffold attempt then succeeded (without my manually doing anything else).

**Comment by wenz** [comment]
Can repro with scaffolding Identity (which has additional issues). The modal error message appears. Upon closing it, you are back to the "Add new Scaffolded item" wizard. Clicking on Add again works then. I'd concur that this is a timing issue. @deepchoudhery is already taking a look AFAIK.

**Comment by deepchoudhery** [comment]
Fixed with .NET 8, 9 scaffolding. Closing.
