### ISSUE TITLE
ASP.NET Core - Scaffolding Item issue

### ISSUE THREAD

**Issue by PagyNeti** [dotnet/Scaffolding#1712]
I have a scaffolding failing issue in Visual Studio 2022 and 2019.

Details:
![Scaffolding-issue](https://user-images.githubusercontent.com/70811082/143558124-f00162ff-1e14-4fca-a4c2-3844c4c793e4.PNG)

The following steps can reproduce the issue🚶:
1. **New Scaffolded Item** -> **Identity** -> **Identity**.
2. Select **Override all files**.
3. Select the proper DbContext from the **Data context class** dropdown.
4. Hit the **Add** button.

The following troubleshooting steps were done by me 🔧 :

1. Downgrade these packages 
- Microsoft.AspNetCore.Identity.EntityFrameworkCore to 5.0.6
- Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation to 5.0.6
- Microsoft.EntityFrameworkCore.Design to 5.0.6
- Microsoft.EntityFrameworkCore.SqlServer to 5.0.6
- Microsoft.EntityFrameworkCore.Tools to 5.0.6
- Microsoft.VisualStudio.Web.CodeGeneration.Design, I tried to downgrade it to 3.1.4, 3.1.5, 5.0.0 and 5.0.1, however, i was not successful, because of the EF package references. Eventually, I could downgrade to 5.0.2, but the same issue came up.
1.1. Cleaned the solution and after that rebuiled it. -> Failed
2.  Tried to keep all of the above mentioned packages at the same package version, 6.0.0 -> Failed
3.  Used the ``dotnet restore`` and ``dotnet tool restore``. -> No luck
4.  Restarted the Visual Studio. -> Failed

Any idea what I am doing wrong?

**Comment by rqueizan** [comment]
I solve similar problem.
Create a new web project, with the same configuration that the original. Scaffold in the new project and copy the generated files and folders to the original folders, review  the code, some using need you fix manually.

**Comment by deepchoudhery** [comment]
fixed with .NET 8 and 9 scaffolding, closing.
