### ISSUE TITLE
Missing "IdentityHostingStartup.cshtml" when scaffolding Identity

### ISSUE THREAD

**Issue by Extragorey** [dotnet/Scaffolding#1714]
### Issue

Identity scaffolding fails with the following error when run by either command line (as below, for any combination of files) or via the IDE context menu (Add -> New Scaffolded Item... -> Identity).

```
> dotnet aspnet-codegenerator identity -dc MyProject.Data.MyContext --files "Account.Login;Account.Logout"

Building project ...
Finding the generator 'identity'...
Running the generator 'identity'...
A file matching the name IdentityHostingStartup.cshtml was not found within any of the folders: C:\Users\Extragorey\.nuget\packages\Microsoft.VisualStudio.Web.CodeGenerators.Mvc\6.0.0\Templates\Identity\Data;C:\Users\Extragorey\.nuget\packages\Microsoft.VisualStudio.Web.CodeGenerators.Mvc\6.0.0\Templates\Identity\Pages;C:\Users\Extragorey\.nuget\packages\Microsoft.VisualStudio.Web.CodeGenerators.Mvc\6.0.0\Templates\Identity
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:07.76
```

### Solution

Manually add *IdentityHostingStartup.cshtml* to the folder specified (*...\.nuget\packages\Microsoft.VisualStudio.Web.CodeGenerators.Mvc\6.0.0\Templates\Identity*), copying it from [this source](https://github.com/dotnet/Scaffolding/blob/main/src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/IdentityHostingStartup.cshtml).
Once added, scaffolding works as expected.

**Suggested:** Include *IdentityHostingStartup.cshtml* in the `Microsoft.VisualStudio.Web.CodeGenerators.Mvc` nuget package distribution.

### Environment Info

**Libraries:** twitter-bootstrap@5.1.3
**Target framework:** .NET 6.0
**IDE:** Visual Studio 2022 17.0.1
**Operating system:** Windows Server 2016 Standard

**Comment by deepchoudhery** [comment]
@Extragorey Hey, tracking this issue for the next update. Will update here when it goes out.

**Comment by N1K1TAS95** [comment]
> ### Issue
> Identity scaffolding fails with the following error when run by either command line (as below, for any combination of files) or via the IDE context menu (Add -> New Scaffolded Item... -> Identity).
> 
> ```
> > dotnet aspnet-codegenerator identity -dc MyProject.Data.MyContext --files "Account.Login;Account.Logout"
> 
> Building project ...
> Finding the generator 'identity'...
> Running the generator 'identity'...
> A file matching the name IdentityHostingStartup.cshtml was not found within any of the folders: C:\Users\Extragorey\.nuget\packages\Microsoft.VisualStudio.Web.CodeGenerators.Mvc\6.0.0\Templates\Identity\Data;C:\Users\Extragorey\.nuget\packages\Microsoft.VisualStudio.Web.CodeGenerators.Mvc\6.0.0\Templates\Identity\Pages;C:\Users\Extragorey\.nuget\packages\Microsoft.VisualStudio.Web.CodeGenerators.Mvc\6.0.0\Templates\Identity
>    at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
>    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
>    at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
>    at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
> RunTime 00:00:07.76
> ```
> 
> ### Solution
> Manually add _IdentityHostingStartup.cshtml_ to the folder specified (_....nuget\packages\Microsoft.VisualStudio.Web.CodeGenerators.Mvc\6.0.0\Templates\Identity_), copying it from [this source](https://github.com/dotnet/Scaffolding/blob/main/src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/IdentityHostingStartup.cshtml). Once added, scaffolding works as expected.
> 
> **Suggested:** Include _IdentityHostingStartup.cshtml_ in the `Microsoft.VisualStudio.Web.CodeGenerators.Mvc` nuget package distribution.
> 
> ### Environment Info
> **Libraries:** twitter-bootstrap@5.1.3 **Target framework:** .NET 6.0 **IDE:** Visual Studio 2022 17.0.1 **Operating system:** Windows Server 2016 Standard

Finally! Worked for me!

**Comment by kandaker** [comment]
Phew! This unblocked me. Thanks for both figuring out the solution, and posting the bug report here!

**Comment by anghelvalentin** [comment]
Thank you.

**Comment by mateuszpiskorz** [comment]
Many thanks! Saved us a lot of time!

**Comment by nkrastev** [comment]
Thank you! Saved me a lot of time!

**Comment by pirocorp** [comment]
Many thanks!

**Comment by anghelvalentin** [comment]
I have written a tutorial about adding identity to an existing ASP.NET application and I have also presented this bug
[https://programmingcsharp.com/implement-identity-on-existing-asp-project/](https://programmingcsharp.com/implement-identity-on-existing-asp-project/)

**Comment by duaneking** [comment]
This is STILL an issue.

**Comment by vijayrkn** [comment]
This is fixed based on the merge commit.
