### ISSUE TITLE
Dotnet MsIdentity tool does not correctly update code templates for Minimal API Web API projects

### ISSUE THREAD

**Issue by zahalzel** [dotnet/Scaffolding#1785]
When "Use controllers (uncheck to use minimal APIs)" is unchecked in Visual Studio, we do not yet have corresponding code update configs for this template and so the Program.cs file is not updated.

![image](https://user-images.githubusercontent.com/75647613/148463599-0cd7735e-dc43-4b7b-9a14-6404ee1708ad.png)

**Comment by Rick-Anderson** [comment]
@zahalzel  can you explain the problem? https://docs.microsoft.com/en-us/aspnet/core/tutorials/min-web-api works as expected and we have many customers confirming it's working.

**Comment by zahalzel** [comment]
> @zahalzel  can you explain the problem? https://docs.microsoft.com/en-us/aspnet/core/tutorials/min-web-api works as expected and we have many customers confirming it's working.

This bug is actually referring to the code updates that we do from the dotnet-msidentity tool that add Microsoft identity platform support, at the moment the tool doesn't add the correct code for a minimal
Web API program.cs file, although I have a fix coming out for this soon.

**Comment by zahalzel** [comment]
@Rick-Anderson updated the title hopefully this is more precise :)
