### ISSUE TITLE
table class="table" is pseudosemantic

### ISSUE THREAD

**Issue by yecril71pl** [dotnet/Scaffolding#1809]
The HTML code produced by the generator is pseudosemantic.
```html
<table class="table">
```

The following tag would be just enough:
```html
<table>
```

**Comment by yecril71pl** [comment]
Blocked by https://github.com/twbs/bootstrap/issues/35824#issue-1130946813.

**Comment by deepchoudhery** [comment]
Apologies for the late response.

We use the bootstrap "table" css so the just using `<table>` instead of `<table class="table">` does remove the table formatting. This would be bootstrap v5.1.0 that we ship in scaffolding for now.

Closing for now.
