### ISSUE TITLE
Missing "IdentityHostingStartup.cshtml" when scaffolding Identity

### ISSUE THREAD

**Issue by dajma00** [dotnet/Scaffolding#1831]
I ran into an issue scaffolding Register identity page into a .NET 6 Blazor hosted app. The issue is same as [issue](https://github.com/dotnet/Scaffolding/issues/1714) #1714. However after I add the missing file as explained in that issue, I get the following error:

```There was an error running the selected code generator: There was an error running the code template c:\users\.....\IdentityHostingStartup.cshtml". Template processing failed: An opening "(" is missing the corresponding closing ")"```

I copied the file from [here](https://github.com/dotnet/Scaffolding/blob/main/src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/IdentityHostingStartup.cshtml).

Target framework: .NET 6.0
Identity Server 4
IDE: Visual Studio 2022 17.0.1
Operating system: Windows 10.

Any pointers as to why this is happening?

**Comment by srosy** [comment]
@dajma00 Ran into the same issue with the same project config. Got it solved by editing the IdentityHostingStartup.cs file and resaving. Here's the edited file if it helps: [IdentityHostingStartup.txt](https://github.com/dotnet/Scaffolding/files/8256664/IdentityHostingStartup.txt). 

For those that don't know where the file should be located, it's around here "C:\Users\{YOUR_USER_NAME}\.nuget\packages\microsoft.visualstudio.web.codegenerators.mvc\6.0.2\Templates\Identity". Your scaffold error will list the exact locations it's checking for the file.

**Comment by vijayrkn** [comment]
The fix is merged. Closing.
