### ISSUE TITLE
Why dotnet-aspnet-codegenerator alway one version behind .NET Runtime?

### ISSUE THREAD

**Issue by doggy8088** [dotnet/Scaffolding#1874]
## Ask a question

The .NET team just release .NET Runtime 6.0.4 today. There are some global tools also release new version with `6.0.4` such as [dotnet-ef](https://www.nuget.org/packages/dotnet-ef/6.0.4), [dotnet-sql-cache](https://www.nuget.org/packages/dotnet-sql-cache/6.0.4) or [Microsoft.dotnet-openapi](https://www.nuget.org/packages/Microsoft.dotnet-openapi/6.0.4).

I'm curious to know that why [dotnet-aspnet-codegenerator](https://www.nuget.org/packages/dotnet-aspnet-codegenerator/6.0.3) don't have a `6.0.4` version? It always one version behind of other tools. Why?

**Comment by vijayrkn** [comment]
[dotnet-aspnet-codegenerator](https://www.nuget.org/packages/dotnet-aspnet-codegenerator/6.0.3) does not have a direct dependency on the .NET runtime packages. So the package numbers are not expected to line up. All servicing updates for Scaffolding will be available in the latest package version.
