### ISSUE TITLE
Minimal API scaffolding should include OpenAPI tags

### ISSUE THREAD

**Issue by jongalloway** [dotnet/Scaffolding#1886]
Scaffolding multiple endpoints with the Minimal API scaffolder doesn't allow filtering by tags, and SwaggerUI view shows all endpoints in one long list.

I would like to see the `WithTags()` statement automatically added. While in the long term this may be solved by https://github.com/dotnet/aspnetcore/pull/41265, the current scaffolding experience should be improved.

I don't believe there is a way to apply the tags at the `IEndpointRouteBuilder ` level, so I would recommend we add `.WithTags(nameof(EndpointsClass))` before the `WithName()` call:

```csharp
public static class SpeakerEndpoints
{
    public static void MapSpeakerEndpoints (this IEndpointRouteBuilder routes)
    {
        routes.MapGet("/api/Speaker", async (ApplicationDbContext db) =>
        {
            return await db.Speakers.ToListAsync();
        })
        .WithTags(nameof(SpeakerEndpoints))
        .WithName("GetAllSpeakers");

        //other route mapping calls
    }
}
```

**Comment by halter73** [comment]
Another option would be to define the endpoint using a static method. This should give you the `SpeakerEndpoints` tag automatically (at least when using Swashbuckle to generate the swagger.json). Here's how we'd update the `SpeakerEndpoints` example:

```csharp
public static class SpeakerEndpoints
{
    public static void MapSpeakerEndpoints (this IEndpointRouteBuilder routes)
    {
        routes.MapGet("/api/Speaker", GetAllSpeakers).WithName(nameof(GetAllSpeakers));
        //other route mapping calls
    }

    public static async Task<List<Speaker>> GetAllSpeakers(ApplicationDbContext db)
    {
        return await db.Speakers.ToListAsync();
    }
}
```

This also has the upside of being more easily unit testable!

You might notice that the `.WithName(nameof(GetAllSpeakers))` seems redudant now that we're passing the `GetAllSpeakers` method group straight to `MapGet`. We [wanted to automatically make the method name the endpoint name and operation id](https://github.com/dotnet/aspnetcore/issues/34540), but we had issues with people using overloaded methods giving multiple endpoints the same name.

Long term, using `MapGroup` to add any metadata you want to all the `"/api/Speaker"` routes makes a lot of sense. I think the scaffolding should how how to do this. Using `MapGroup` and static methods isn't mutually exclusive either. With `MapGroup` you could do something like:

 ```csharp
public static class SpeakerEndpoints
{
    public static void MapSpeakerEndpoints (this IEndpointRouteBuilder routes)
    {
        var speakerGroup = routes.MapGroup("/api/Speaker");
        // Note you'd probably want to add some metadata other than group name unless the goal is
        // to generate multiple swagger.json docs: https://github.com/dotnet/aspnetcore/issues/36414
        speakerGroup.WithGroupName(nameof(SpeakerEndpoints));

        speakerGroup.MapGet("/", GetAllSpeakers).WithName(nameof(GetAllSpeakers));
        //other route mapping calls
    }

    public static async Task<List<Speaker>> GetAllSpeakers(ApplicationDbContext db)
    {
        return await db.Speakers.ToListAsync();
    }
}
```

**Comment by jongalloway** [comment]
@captainsafia @DamianEdwards Thoughts?

I ran into this updating the ASP.NET workshop to .NET 6 + minimal. Scaffolding multiple models ends up with a single long list, and adding Open API tags requires updating every single MapXXX() call.

**Comment by DamianEdwards** [comment]
@davidfowl explicitly didn't like the idea of the scaffolding producing methods as opposed to the lambdas, but I agree the benefit of the tags per class is nice. What if we just go with the original suggestion of adding  `.WithTags(nameof(SpeakerEndpoints))` for now, and when we update scaffolding for 7.0 do what @halter73 suggests and put them in a group so that it only has to be added once.
