### ISSUE TITLE
Minimal API scaffolders do not provide --useSqlite option

### ISSUE THREAD

**Issue by mrward** [dotnet/Scaffolding#1897]
Other scaffolders provide an option to use Sqlite instead of Sql server. The minimal api scaffolder for EF does not and always uses Sql server.

https://github.com/dotnet/Scaffolding/pull/1848/files#diff-33030d3cf7158d5a01510acbb964fdd0c78d8a7aafda8a15c06b795d6e2cb2feR91

Add a --useSqlite option to the minimal api scaffolder for EF.

**Comment by deepchoudhery** [comment]
@mrward Has the fix been working?

**Comment by vijayrkn** [comment]
@deepchoudhery to verify if this support is available now or not.

**Comment by mrward** [comment]
@deepchoudhery We have enabled minimal api support in VS Mac now that sqlite is working. Thanks :)

**Comment by vijayrkn** [comment]
@mrward - Thanks for confirming. Closing the issue.
