### ISSUE TITLE
dotnet-aspnet-codegenerator razorpage - "A type with the name Movie does not exist"

### ISSUE THREAD

**Issue by ljm000** [dotnet/Scaffolding#1904]
Here's an ASP.NET Core tutorial from the Microsoft docs:
https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-6.0&tabs=visual-studio

Code:
<pre>
using System.ComponentModel.DataAnnotations;

namespace RazorPagesMovie.Models
{

    public class Movie
    {
        public int ID { get; set; }
        public string Title { get; set; }
        [DataType(DataType.Date)]
        public DateTime ReleaseDate { get; set; }
        public string Genre { get; set; } = string.Empty;
        public decimal Price { get; set; }
    }

}
</pre>

Command:
<pre>
dotnet tool uninstall --global dotnet-aspnet-codegenerator
dotnet tool install --global dotnet-aspnet-codegenerator
dotnet tool uninstall --global dotnet-ef
dotnet tool install --global dotnet-ef
dotnet add package Microsoft.EntityFrameworkCore.Design
dotnet add package Microsoft.EntityFrameworkCore.SQLite
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design
dotnet add package Microsoft.EntityFrameworkCore.SqlServer
</pre>

<pre>
dotnet-aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages/Movies --referenceScriptLibraries -sqlite
</pre>

Error message:
<pre>
Building project ...
Finding the generator 'razorpage'...
Running the generator 'razorpage'...
A type with the name Movie does not exist
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:06.18
</pre>

dotnet info:
<pre>
 Version:   6.0.104
 Commit:    915d644e45
 OS Name:     Mac OS X
 OS Version:  12.3
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /opt/homebrew/Cellar/dotnet/6.0.104_1/libexec/sdk/6.0.104/

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  6.0.104 [/opt/homebrew/Cellar/dotnet/6.0.104_1/libexec/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.4 [/opt/homebrew/Cellar/dotnet/6.0.104_1/libexec/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.4 [/opt/homebrew/Cellar/dotnet/6.0.104_1/libexec/shared/Microsoft.NETCore.App]
</pre>

IDE:Visual Studio Code 1.67.2

**Comment by vijayrkn** [comment]
This is fixed : https://github.com/dotnet/Scaffolding/pull/1893/files

**Comment by seanpmcn** [comment]
I am doing this tutorial and I am having this issue as well.
