### ISSUE TITLE
 Feedback on generated content from scaffolders for RC2

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/Scaffolding#193]
FYI we are asking for feedback on generated content at https://github.com/aspnet/Tooling/issues/444.

I added this issue here to notifiy watchers of this repo. I will close this issue in a few days.

**Comment by barrytang** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=232588&fullScreen=false&_a=edit">232588</a>

**Comment by Eilon** [comment]
Removing from milestone because this milestone already shipped.

**Comment by deepchoudhery** [comment]
Closing, content is up to date.
