### ISSUE TITLE
Scaffolding minimal api should use lower case parameter names for generated lambdas

### ISSUE THREAD

**Issue by geometrikal** [dotnet/Scaffolding#1954]
Scaffolding minimal api from class with primary key `Id` capitalises method parameter but uses lower case for route pattern. This causes Connect Services OpenAPI code generation (NSwag) to generate erroneous code.

### Steps to reproduce

1. Create simple dto

```
public class Dto
{
    public string Id { get; set; }
}
```

2. Scaffold minimal api with read/write endpoints using Entity Framework and OpenAPI enabled. Code generated will look like this:

```
routes.MapGet("/api/Dto/{id}", async (string Id, PerceptionAnnotationServerContext db) =>
        {
            return await db.Dto.FindAsync(Id)
                is Dto model
                    ? Results.Ok(model)
                    : Results.NotFound();
        })
        .WithName("GetDtoById")
        .Produces<Dto>(StatusCodes.Status200OK)
        .Produces(StatusCodes.Status404NotFound);
```

Note the parameter name `Id` instead of `id`. If scaffolding using controllers, the lower case version is used.

Using `dotnet swagger` to generate the open api json results in route with lower case, but parameter name capitalised. This in turn causes NSwag to generate incorrect code, where they try to replace `{Id}` but should be replacing `{id}`

```
var urlBuilder_ = new System.Text.StringBuilder();
urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/api/Dto/{id}");
urlBuilder_.Replace("{Id}", System.Uri.EscapeDataString(ConvertToString(id, System.Globalization.CultureInfo.InvariantCulture)));
```

Microsoft.VisualStudio.Web.CodeGeneration.Design/Microsoft.DotNet.MSIdentity version: 6.0.6
Target framework:  .NET 6.0
Operating system: Windows 11
IDE: Visual Studio 2022

**Comment by vijayrkn** [comment]
I see that this change is already merged. Closing.
