### ISSUE TITLE
Error adding Azure AD auth to Blazor Server app

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/Scaffolding#1960]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Error-adding-Azure-AD-auth-to-Blazor-Ser/10091177)._

---
Repro steps:
- Create a new Blazor Server project without authentication
- Add Connect Service > Microsoft Identity Platform
- Register a new app
- Accept the rest of the defaults

Actual result:
![image](https://user-images.githubusercontent.com/219224/179302342-a1c3020e-0620-4207-a712-fac55ddf7204.png)

---
#### Feedback Bot on 7/10/2022, 11:01 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by vijayrkn** [comment]
This should be resolved. I just tried the scenario and it works.
