### ISSUE TITLE
vs2022 17.3.4 scaffold identity

### ISSUE THREAD

**Issue by bxjg1987** [dotnet/Scaffolding#2025]
i have a exists asp.net core 6.0 blazor server application
and then add identity scaffold 
i got this error
![image](https://user-images.githubusercontent.com/39435771/191771364-fe271cb7-5b07-4c5a-b213-ab1927a01b2f.png)

**Comment by CronoxJC** [comment]
Unload the proyects, when you finish, load again

**Comment by devLarka** [comment]
experiencing the same issue

**Comment by everstudybee** [comment]
> i have a exists asp.net core 6.0 blazor server application and then add identity scaffold i got this error ![image](https://user-images.githubusercontent.com/39435771/191771364-fe271cb7-5b07-4c5a-b213-ab1927a01b2f.png)

Duplicate thread https://github.com/dotnet/Scaffolding/issues/2019

**Comment by fredimachado** [comment]
The issue seems to be fixed in `6.0.10`.

**Comment by vijayrkn** [comment]
Fixed in 6.0.10 version of the package.
