### ISSUE TITLE
Scaffolding failed. Could not load information for project

### ISSUE THREAD

**Issue by erdincefeturhan** [dotnet/Scaffolding#2027]
i have this problem Can you let me know when it's resolved?

good work

**Comment by rezamap** [comment]
I have the same problem

**Comment by Urien2017** [comment]
same problem too

**Comment by GatitoStudio** [comment]
Same probleme , i have a second project for my model class

**Comment by davebeland** [comment]
Same problem here

**Comment by davebeland** [comment]
I have the same problem

**Comment by everstudybee** [comment]
Duplicate thread https://github.com/dotnet/Scaffolding/issues/2019

**Comment by everstudybee** [comment]
> i have this problem Can you let me know when it's resolved?
> 
> good work

Duplicate thread https://github.com/dotnet/Scaffolding/issues/2019

**Comment by mudouasenha** [comment]
Same problem, thanks @everstudybee for the duplicate reference.

**Comment by agina** [comment]
Error Is here 
![scafold](https://user-images.githubusercontent.com/37777742/192352031-b139e700-e76c-4a5a-bcc2-3ca8fe690333.png)
Solution is here
https://www.youtube.com/watch?v=gpusjEBzzSw

**Comment by fredimachado** [comment]
The issue seems to be fixed in `6.0.10`.

**Comment by rezamap** [comment]
Yes, I checked it with 6.0.10 and it’s solved.

Thank you

**Comment by mikehengetech** [comment]
I updated Microsoft.VisualStudio.Web.CodeGeneration.Design from 6.0.9 to 6.0.10  ,but it kept coming back to 6.0.9 !?
keep showing this Error:
![image](https://user-images.githubusercontent.com/97877231/193067500-e9730a64-bc85-4fda-856f-2dd29f081dbe.png)
And this Error:
![image](https://user-images.githubusercontent.com/97877231/193066922-0cb0ca3f-8fd3-4e28-863f-34c302d3c146.png)

Solution:
install this: Microsoft.VisualStudio.Web.CodeGeneration.Utils v6.0.10
for ( Microsoft.VisualStudio.Web.CodeGeneration.Design v6.0.10) (version could be different v6.0.10)
just like here: https://www.youtube.com/watch?v=46mZCEHgBK4

**Comment by vijayrkn** [comment]
@mikehengetech - Can you confirm what all package references you have in your project? You only need reference to the codegenerator.design package and you need to update the version to 6.0.10.

**Comment by virus611** [comment]
> The issue seems to be fixed using Microsoft.VisualStudio.Web.CodeGeneration.Design `6.0.10`.

Nice!   6.0.10 is ok。
