### ISSUE TITLE
dotnet aspnet-codegenerator failing when DbContext is in another library

### ISSUE THREAD

**Issue by vorodot** [dotnet/Scaffolding#2034]
Hi, 
I face an issue but running scaffolding for Identity when the DbContext is moved to a referenced library
Everything is fine when the DbContext is in the same web project.
The error is that "Could not load information for project ReferencedClassLibrary" - the one with the moved DB context

The sample projects is attached as zip [WebApplicationWithDbContextInside.zip](https://github.com/dotnet/Scaffolding/files/9690504/WebApplicationWithDbContextInside.zip).
In [StackOverflow](https://stackoverflow.com/questions/73739455/scaffolding-minimal-api-with-a-separate-dbcontext-project-throws-error-could-no#comment130488138_73739455) there is an unresolved topic for that from the last few days.

This is the trace of the output:

> [Trace]: Command Line: --project D:\Projects\Tests\Scaffolding\Source code\WebApplicationWithDbContextInside\WebApplicationWithDbContextInReferencedLibrary\WebApplicationWithDbContextInReferencedLibrary.csproj --no-build --port-number 56471 identity --dbContext ClassLibraryWIthDbContext.Data.ApplicationDbContext --files Account.Register --generateLayout --force --dispatcher-version 2.0.0 --no-dispatch --simulation-mode
Scaffolding failed.
Could not load information for project D:\Projects\Tests\Scaffolding\Source code\WebApplicationWithDbContextInside\ClassLibraryWIthDbContext\ClassLibraryWIthDbContext.csproj
[Trace]:    at Microsoft.VisualStudio.Web.CodeGeneration.Utils.RoslynWorkspaceHelper.GetProjectReferenceInformation(IEnumerable`1 projectReferenceStrings)
   at Microsoft.VisualStudio.Web.CodeGeneration.Utils.RoslynWorkspace..ctor(IProjectContext projectInformation, String configuration)
   at Microsoft.VisualStudio.Web.CodeGeneration.Design.CodeGenCommandExecutor.AddFrameworkServices(ServiceProvider serviceProvider, IProjectContext projectInformation)
   at Microsoft.VisualStudio.Web.CodeGeneration.Design.CodeGenCommandExecutor.Execute(Action`1 simModeAction)
   at Microsoft.VisualStudio.Web.CodeGeneration.Design.Program.<>c__DisplayClass4_0.<<Execute>b__0>d.MoveNext()

Steps to reproduce:
1) Configure
1.1) Create a new solution with a new web .NET 6.0 project inside (MVC project with authentication type "Individual Accounts")
1.2) Add new second web .NET 6.0 project inside (MVC project with authentication type "Individual Accounts")
1.2.1) Create a new Class Library Project .NET 6.0
1.2.2) Add project reference in the second web project pointing to the class library created in 1.2.1
1.2.3) Cut Data directory from the second web project and paste in in the class library.
1.2.4) Rename all namespaces in Data directory to match the name of the project.
1.2.5) Fix the Project.cs in the second web project to include the namespace to the Data area from the class library
1.2.6) In Project.cs during the configuration of the UseSqlServer add instruction for the EF migration
2) Test
2.1) Run "New Scaffolding Item" from File->New for the first project.
2.1.1) Select "Identity" in the dialog box
2.1.2) Choose at least one option from section "Choose files to override"
2.1.3) Select the only one DB context
2.1.4) Press "Add" button and observe that after awhile the file is overridden (attached img 1)
2.2) Repeat all the steps from 2.1 for the second project and observe that the adding is failing (attached img  2 and 3)

Very thanks about the help in advance.
Boris

(img 1)
![img 1](https://user-images.githubusercontent.com/12648318/193413402-ba8952a9-0dfe-42d6-b629-32b8fef9367b.png)

(img 2)
![img 2](https://user-images.githubusercontent.com/12648318/193413407-6f20b50e-3e81-4133-8900-e11f7f509078.png)

(img 3)
![img 3](https://user-images.githubusercontent.com/12648318/193413409-bc30ec68-1689-4530-8c35-8cc90f0a1750.png)

**Comment by vorodot** [comment]
> @vorodot - Can you please the package references in the csproj? There was a recent issue and has seen been fixed in the 6.0.10 version of the codegenerator.design package
> 
> ```
> https://www.nuget.org/packages/Microsoft.VisualStudio.Web.CodeGeneration.Design/6.0.10
> ```

When I do that during the scaffolding operation the package is automatically downgraded to version 6.0.9
See that [video](https://vorodot-gmail.tinytake.com/msc/NzQxNTY4M18yMDMwNjM3MQ)

The first project with the DBContext inside is scaffolding fine. The one with the DBContext in another library during scaffolding downgrading the version of the library and fails

**Comment by vorodot** [comment]
Sorry, first time working with Github. I didnt wanted to close it.

**Comment by vijayrkn** [comment]
@deepchoudhery - How can @vorodot ensure that 6.0.10 version is not downgraded to a lower version?

**Comment by deepchoudhery** [comment]
@vorodot what version of VS are you on? We fixed this issue in a newer VS versions, I'll find the exact one

**Comment by vorodot** [comment]
> @vorodot what version of VS are you on? We fixed this issue in a newer VS versions, I'll find the exact one

Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.2.6

**Comment by deepchoudhery** [comment]
@vorodot I think we released this fix in 17.3 time, I can confirm the auto-downgrade is not an issue in 17.3.4. Would you be against updating your VS to 17.3.4 (I believe the latest update rn)?

**Comment by vorodot** [comment]
I've just updated to the latest VS version - 17.3.5
With version of the library 6.0.10 it is fixed.

Thanks for the fast work.
