### ISSUE TITLE
Changes for .NET 7 minimal API scaffolders

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/Scaffolding#2037]
- Add whitespace route group definition and first API definition
- Remove all `Produces` extension method calls (they aren't needed when using `TypedResults` or returning the object to be serialized directly)
- Remove all calls to `WithTags` from API definitions and instead have single call on the group definition
- Move call to `WithOpenApi` from group definition to API definitions (that method is designed to allow editing a specific `OpenApiOperation` so is more useful on the endpoint definitions directly IMO)
- Update non-EF Core scaffolder to also use `TypedResults`
- Question: Do we want to add an option for using strongly typed results?
  - My thinking is "yes" because they represent an alternate of writing the API but not necessarily a "better" way and some folks may prefer using `Results` and the `Produces` approach

**Comment by DamianEdwards** [comment]
FYI @deepchoudhery @vijayrkn @JeremyLikness

**Comment by deepchoudhery** [comment]
@DamianEdwards Working on getting these in for 7.0 GA. I do not have enough feedback on your question regarding strongly typed results, so I think you all should make that call.

**Comment by DamianEdwards** [comment]
@deepchoudhery if we're able to get that option added (simple boolean checkbox "Use TypedResults") then I think we should do it. If it's going to increase the work such that it will push this out past GA then we should leave it out for now and just do the TypedResults version.

@JeremyLikness thoughts?

**Comment by JeremyLikness** [comment]
+1 on the checkbox. Let's give the flexibility to choose unless it compromises GA. Also concur fallback s/b TypedResults.

**Comment by deepchoudhery** [comment]
some sample dialogs for the proposed change on the VS side. On the cmd line, it'll be another option that is passed.

Non ef dialog, showing checkbox for TypedResults:
<img width="488" alt="NeMK9OfMsT" src="https://user-images.githubusercontent.com/54324771/196535617-1d072494-625b-4d38-b20d-40958b9e280f.png">

Ef dialog, showing as launched:
<img width="488" alt="yZGtSBWpJX" src="https://user-images.githubusercontent.com/54324771/196535703-4f6a9e8f-0b68-476d-b8db-9d1c44e3800d.png">

Ef dialog, showing with existing db, sqlite disabled as its only allowed for new dbs:
<img width="488" alt="e2UPOoN34M" src="https://user-images.githubusercontent.com/54324771/196535781-3a33a502-95de-48ce-865e-e87b03e19156.png">

Ef dialog, showing with new db and sqlite checked:
<img width="488" alt="e2UPOoN34M" src="https://user-images.githubusercontent.com/54324771/196535835-77038019-561e-4437-bbd2-05c6e5e0b46d.png">

**Comment by DamianEdwards** [comment]
Capturing feedback from meeting today:

- Make the database choice a drop-down list that's only populated & enabled when a new data context class is being created. If an existing context class is selected, disable the drop-down list and make the selected item text like "Configured by DbContext"
- OpenAPI does not have a space in it
- Add tooltips to all labels/controls that describes in more detail what they do
- Default the "Use TypedResults" and "Enable OpenAPI" checkboxes to checked/true

**Comment by deepchoudhery** [comment]
> Capturing feedback from meeting today:
> 
> * Make the database choice a drop-down list that's only populated & enabled when a new data context class is being created. If an existing context class is selected, disable the drop-down list and make the selected item text like "Configured by DbContext"
> * OpenAPI does not have a space in it
> * Add tooltips to all labels/controls that describes in more detail what they do
> * Default the "Use TypedResults" and "Enable OpenAPI" checkboxes to checked/true

this is almost all exclusively VS changes so maybe I'll open a ticket on that side of the world once we get the TypedResults changes in and close this.

**Comment by deepchoudhery** [comment]
All these have been addressed I believe, for anything else let's use new(er) issues. Thanks.
