### ISSUE TITLE
Microsoft.DotNet.Scaffolding.Shared 7.0.0 -> Microsoft.CodeAnalysis.CSharp.Features 4.0.0

### ISSUE THREAD

**Issue by MCFHTAGENTS** [dotnet/Scaffolding#2122]
Microsoft.DotNet.Scaffolding.Shared 7.0.0 seems to have a dependency on Microsoft.CodeAnalysis.CSharp.Features 4.0.0
and yet Microsoft.CodeAnalysis.CSharp.Features 4.4.0 is the current version

This is preventing me use the 4.4 in my own code. 4,0.0 has also been withdrawn so at the very least this should reference 4.0.1 as I can't easily install 4.0.0

**Comment by deepchoudhery** [comment]
Fixed in an upcoming servicing update next week. Wondering what the issue was anyways? If you needed to use `Microsoft.CodeAnalysis.CSharp.Features` v4.4.0, did you not have a `PackageReference` for that specific version? That should suppressed any downgrade issues.

**Comment by deepchoudhery** [comment]
Fixed, closing (7.0.1 package out today)
