### ISSUE TITLE
Error in API scaffolder when model type uses the `required` keyword

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/Scaffolding#2133]
Found using latest Visual Studio INT PREVIEW or PREVIEW build.

1. Create a new ASP.NET Core Web API project targeting .NET 7 without controllers (aka Minimal APIs)
2. Add the following model type declaration to `Program.cs` (note the `required` keyword on the `Title` property):
    ```csharp
    public class Todo
    {
        public int Id { get; set; }
        public required string Title { get; set; }
        public bool IsComplete { get; set; }
    }
    ```
3. Invoke the "API with read/write endpoints, Entity Framework" scaffolder via the "Add Scaffolded Item" project context menu
   - Select the `Todo` type as the model class
   - Select to create a new endpoints class with the default name
   - Select to create a new data context class with the default name
   - Leave other options at their default values
4. The following error dialog is displayed:
    <img width="313" alt="image" src="https://user-images.githubusercontent.com/249088/205157329-45421e26-79cc-4d5c-96c3-f935504042cf.png">
    ```
    ---------------------------
    Microsoft Visual Studio
    ---------------------------
    Error
    
    There was an error running the selected code generator:
    
    'There was an error creating a DbContext :C:\Users\damia\source\repos\WebApplication109\WebApplication109\Program.cs(31,21): error CS1519: Invalid token 'string' in class, record, struct, or interface member declaration'
    ---------------------------
    OK   
    ---------------------------
    ```

**Comment by deepchoudhery** [comment]
Fixed, verified in VS 17.4.3 and VS 17.5 Preview 2 (newer 7.0.1 packages)
