### ISSUE TITLE
Update jQuery to v3.5.1 in Microsoft.VisualStudio.Web.CodeGenerators.Mvc.2.1.*

### ISSUE THREAD

**Issue by martinknafvework** [dotnet/Scaffolding#2235]
When using ASP.NET Core with .NET Framework, the latest supported version of `Microsoft.VisualStudio.Web.CodeGenerators.Mvc` is 2.1.10. This version contains a jQuery version with vulnerabilities (in the folder `\Templates\Identity\wwwroot\lib\jquery`).

There has been previous issues raised that jQuery should be updated due to these vulnerabilities, but then it's only been made on later versions of the "Microsoft.VisualStudio.Web.CodeGenerators.Mvc"-library, for example:

* https://github.com/dotnet/Scaffolding/issues/1000
* https://github.com/dotnet/Scaffolding/issues/1327

When using ASP.NET Core with .NET Framework, it's not possible to upgrade Microsoft.VisualStudio.Web.CodeGenerators.Mvc to a version where the issue has been fixed, since those versions are either not compatible with .NET Framework or not supported. Since the 2.1.x-branch of `Microsoft.VisualStudio.Web.CodeGenerators.Mvc` is still officially supported, and it's not possible to upgrade to 2.2 or later versions, then it looks to me like a 2.1.11-version should be released with updated jQuery.

The fact that the 2.1.x-branch is still officially supported is specified here:
https://dotnet.microsoft.com/en-us/platform/support/policy/aspnetcore-2.1

While it is possible to upgrade jQuery manually after code-generation is done, the library Microsoft.VisualStudio.Web.CodeGenerators.Mvc is considered vulnerable by 3rd party software such as Azure Component Governance and Mend/WhiteSource (which leads to alert being triggered in those systems if it's used).

**Comment by nitramavfank** [comment]
Will there be some acknowledgement that this issue will be fixed? (Sorry, I don't know what process is being followed when it comes to issues in this repo.)

**Comment by deepchoudhery** [comment]
Apologies for the delay, will be fixed for `Microsoft.VisualStudio.Web.CodeGenerators.Mvc` package with a servicing for 2.1.x in the next coming weeks.

**Comment by nitramavfank** [comment]
@deepchoudhery, you mentioned in February it would be fixed in the next coming weeks. So far, 2.1.10 is still the latest 2.1-version. Do you know when 2.1.11 will be released?

**Comment by nitramavfank** [comment]
@deepchoudhery - ping pong?

**Comment by deepchoudhery** [comment]
@martinknafvework hey, .NET 2.1 is out of support so we will not be updating the jQuery content for this version. It has been updated for .NET 6, 8, and 9.

**Comment by martinknafvework** [comment]
ASP.NET Core 2.1 is still fully supported by Microsoft, since it's the latest version of ASP.NET Core which is compatible with .NET Framework. I linked the support policy in the original post, and it still shows that 2.1 is supported: https://dotnet.microsoft.com/en-us/platform/support/policy/aspnet/2.1-packages

The following announcement from October also mentions that 2.1 is supported:
https://github.com/dotnet/announcements/issues/331
> Since 2021, ASP.NET Core 2.1 is supported only when running on .NET Framework.

So can you clarify what you mean by ".NET 2.1 is out of support"?
