### ISSUE TITLE
VS Mac, fails to add scaffolding when using mssql. Always tries to add the -sqlite flag

### ISSUE THREAD

**Issue by chevol** [dotnet/Scaffolding#2239]
Simple API project based off starting project. Added EF and DB connection. I can add Controller manually and everything works fine but when I attempt to "Add Scaffolding" It always tries to add the '-sqlite" flag to the end of the command and thus failing.  Is there a way to stop this because my project is using mssql?

### Include stack traces

```
Building project…
Running /Users.../HotelListing.API/HotelListing.API/obj/dotnet-aspnet-codegenerator --configuration "Debug" --project "/Users.../HotelListing.API/HotelListing.API/HotelListing.API.csproj" controller --model Hotel --dataContext HotelListingDbContext -name HotelsController --no-build -outDir "/Users.../HotelListing.API/HotelListing.API" --controllerNamespace HotelListing.API --restWithNoViews  --useSqlite 
Finding the generator 'controller'...
Running the generator 'controller'...
Specify --help for a list of available options and commands.
Unrecognized option '--useSqlite'
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, String[] args, Int32 index, String argTypeName, Boolean ignoreContinueAfterUnexpectedArg)
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:02.66

Unrecognized option '--useSqlite'

```

### Include provider and version information

Microsoft.VisualStudio.Web.CodeGeneration.Design/Microsoft.DotNet.MSIdentity version:
Target framework: .NET 7.0
Operating system: MAC
IDE: Visual Studio 17.4.2 (build 17)

**Comment by vijayrkn** [comment]
@deepchoudhery - Please work with the VS Mac team to sort this out.

**Comment by mrward** [comment]
Tried a low risk fix in VS Mac to use `-sqlite` instead. Scaffolding then seems to fail later on with a different error:

CS1061: 'DbContextOptionsBuilder' does not contain a definition for 'UseSqlite' and no accessible extension method 'UseSqlite' accepting a first argument of type 'DbContextOptionsBuilder' could be found (are you missing a using directive or an assembly reference?)

This is with .NET 7.0.102, .NET 6.0.405 installed, and the latest scaffolding packages used as defined by the online scaffolding.json.

```
  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="7.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="7.0.2" />
  </ItemGroup>
```

**Comment by deepchoudhery** [comment]
Hey @mrward, I was unaware of mssql support for VS Mac if the Program.cs/Startup.cs is configured for mssql as in @chevol, the scaffolding will fail to activate the DbContext since it will be looking for a `UseSqlite` call which is missing. 
I'll take a deeper look today @mrward and we'll service this ASAP, apologies.

**Comment by deepchoudhery** [comment]
Addressing #2241

**Comment by chevol** [comment]
Thanks!

**Comment by MSicc** [comment]
I am sorry but the bug is not yet resolved.

With VS 17.5.6(build 3), the scaffolder still adds sqlite as provider automatically.

**Comment by mrward** [comment]
@MSicc VS Mac 17.5.6 adding sqlite when scaffolding for EntityFramework is expected. This bug was about the scaffolding failing when adding sqlite, which has been fixed.

**Comment by MSicc** [comment]
@mrward why whould I need sqlite if I explicitly call UseSqlServer? and the original question was also about MSSQL, that's why I added my comment here. Trying to scaffold an API Controller with actions, using Entity Framework.

**Comment by mrward** [comment]
VS Mac has no support for scaffolding for SQL Server, and will always use Sqlite. That is currently a limitation of VS Mac, not dotnet scaffolding. It might be worth filing a feedback ticket for Visual Studio for Mac https://developercommunity.visualstudio.com/VisualStudioMac/suggest

**Comment by MSicc** [comment]
very strange, because if I choose Razor Pages with Entity Framework, I do not have these Problems...
