### ISSUE TITLE
Scaffolding should autogenerate a migration

### ISSUE THREAD

**Issue by rustd** [dotnet/Scaffolding#224]
**Repro steps:**
- Create ASP.NET Core Web App with Individual Auth
- Add a model class
- Scaffold a controller with EF option to generate controllers and views
- Run the app and navigate to the controller

**Actual**
You will see this an error from EF to generate and apply the migrations using commandline.
**Expected**
The scaffolding tool can have an option of generating/ applying the migrations during the scaffolding process.
This will help improve the experience of scaffolding where a user can handle the migration case during scaffolding rather than running the app and having it fail

**Comment by barrytang** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=232594&fullScreen=false&_a=edit">232594</a>

**Comment by deepchoudhery** [comment]
the experience on VS using 'Connected Services --> Add Migration/Update database' and the same on commandline using the 'dotnet ef' tool are pretty stable and good experiences. Scaffolding should stick to content generation/modification. There is messaging to perform above actions in the blazor/razor pages if they are not performed. Not a feature we want to add, closing.
