### ISSUE TITLE
Scaffold sealed classes

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/Scaffolding#2251]
Currently scaffolded classes are not sealed.

Consider sealing the scaffolded classes with the `sealed` modifier keyword.

**Comment by deepchoudhery** [comment]
Hey @vanillajonathan, there is no particular reason why we need to block inheritance for scaffolded controllers/view models/endpoints. If a developer wants to block inheritance, adding a sealed modifier is quite easy and we would leave that to you.

Any particular reason why to add `sealed` modifier by default?

**Comment by vanillajonathan** [comment]
You wouldn't block inheritance since anyone who would want use inheritance could just remove the sealed keyword from the scaffolded classes.

The reason to add the `sealed` modifier by default is that my understanding is that it providedes numerous performance benefits, and that Microsoft have moved in the direction of sealed classes as can be seen in the [/dotnet/runtime](https://github.com/dotnet/runtime) repository where the internal and private classes are now sealed.

See https://github.com/dotnet/runtime/pull/49958 and https://github.com/dotnet/runtime/issues/49944

**Comment by deepchoudhery** [comment]
Cool makes sense for perf reasons for sure, was not aware of Microsoft/dotnet moving in this direction, ty for the info. Will be looking to service this next month.

**Comment by deepchoudhery** [comment]
Hey,
this is a very easy fix on the developer side of things so will be closing this. 
if there is a next iteration of templates, I will switch them all to sealed. 

Thanks for you input,
Deep
