### ISSUE TITLE
SimulationModeFileSystem FileExists Doesn't Recognize Files it Created

### ISSUE THREAD

**Issue by brandoncorrea** [dotnet/Scaffolding#2306]
First of all, thank you for this excellent tool. It's been working great for me right up until this afternoon.

I was getting a strange failure in my tests while using [`SimulationModeFileSystem.FileExists`](https://github.com/dotnet/Scaffolding/blob/fe75212e65ccff4ebf308a3a6f200959da80b84a/src/Scaffolding/VS.Web.CG.Core/SimulationModeFileSystem.cs#L73). Could someone tell me if this is a bug or if my assumptions below are correct?

My assumption is that if a file is created via [`SimulationModeFileSystem.WriteAllText`](https://github.com/dotnet/Scaffolding/blob/fe75212e65ccff4ebf308a3a6f200959da80b84a/src/Scaffolding/VS.Web.CG.Core/SimulationModeFileSystem.cs#L98) (or any  of the creation methods for that matter), then `FileExists` should return `true` for that file.

This NUnit test is Passing, but should be Failing.

```C#
[Test]
public void DoesNotRecognizeFilesWrittenTo()
{
    var fileSystem = SimulationModeFileSystem.Instance;
    var path = @".\foo.txt";
    fileSystem.WriteAllText(path, "bar");
    Assert.IsFalse(fileSystem.FileExists(path));
    Assert.Throws<IOException>(() => fileSystem.DeleteFile(path));
}
```

This NUnit test is Failing on `DeleteFile`, but should be Passing.

```C#
[Test]
public void RecognizesAndDeletesFilesWrittenTo()
{
    var fileSystem = SimulationModeFileSystem.Instance;
    var path = @".\foo.txt";
    fileSystem.WriteAllText(path, "bar");
    Assert.IsTrue(fileSystem.FileExists(path));
    fileSystem.DeleteFile(path);
    Assert.IsFalse(fileSystem.FileExists(path));
}
```

If I understand the problem correctly, then the fix should be something like this: checking the virtual file system before checking the physical file system.

```C#
public bool FileExists(string path)
{
    return 
        FileSystemChanges.Any(
            f => f.FullPath.Equals(path, PathComparisonType) 
            && f.FileSystemChangeType == FileSystemChangeType.AddFile)
        || File.Exists(path)
        && (!FileSystemChanges.Any(
            f => f.FullPath.Equals(path, PathComparisonType)
            && f.FileSystemChangeType == FileSystemChangeType.DeleteFile));
}
```

Here is what `FileExists` currently looks like, as of writing this:

```C#
public bool FileExists(string path)
{
    return File.Exists(path)
        && (!FileSystemChanges.Any(
            f => f.FullPath.Equals(path, PathComparisonType)
            && f.FileSystemChangeType == FileSystemChangeType.DeleteFile));
}
```

### Versions

Microsoft.VisualStudio.Web.CodeGeneration.Core version: 7.0.4
Target framework: .NET 7.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.5.0

**Comment by deepchoudhery** [comment]
Hey,
I'm not the author of this portion of the repo but the `SimlationModeFileSystem`'s purpose is that it `Records all the changes requested for the fileSystem, without persisting the changes on disk.` The fileSystem is still expected to be on disk and all these changes are eventual disk operations. 

There is no virtual filesystem unfortunately, not sure if that would be useful for this tool or what purpose it would serve (since IFileSystem) is mockable for testing already. 

Let me know if that makes sense and if you have any ideas, please reopen the issue. Thanks for the feedback!
