### ISSUE TITLE
Incorrect uri in generated Post scaffold

### ISSUE THREAD

**Issue by phenning** [dotnet/Scaffolding#2377]
When scaffolding a Person model, the TypedResults or Result should contain the uri considering the mapped group.

The following is generated:

```
        group.MapPost("/", (Person model) =>
        {
            //return TypedResults.Created($"/Persons/{model.ID}", model);
        })
        .WithName("CreatePerson")
        .WithOpenApi();
```

instead of

```
        group.MapPost("/", (Person model) =>
        {
            //return TypedResults.Created($"/api/Person/{model.ID}", model);
        })
        .WithName("CreatePerson")
        .WithOpenApi();
```

even though the following is earlier in the method.
`        var group = routes.MapGroup("/api/Person").WithTags(nameof(Class));`
        
       
Additionally if the Person model contains an "Id" property instead of "ID", when uncommenting the generated code, it will result in a compile error.

**Comment by deepchoudhery** [comment]
easy fix, will do soon.

**Comment by deepchoudhery** [comment]
fixed for .NET 6, 7, and 8 Preview 5. Releasing next week. Closing.
