### ISSUE TITLE
Microsoft.visualstudio.web.codegenerators.mvc.6.0.16 includes vulnerable and outdated jquery-validate library

### ISSUE THREAD

**Issue by chrish** [dotnet/Scaffolding#2516]
Apologies in advancde if this is the wrong place; please let me know where to go if this is the case. 

.NET 6 is still supported, and a the default Web Application project template for .NET 6 includes microsoft.visualstudio.web.codegenerators.mvc.6.0.16 which is the most recent release for this .NET version. This component includes jquery-validate version 1.17.0 which is vulnerable. While it is possible to update to the most recent release once installed, alerts are still triggered by tools such as Sonatype Firewall. 

Can a version 6.0.17 be released to fix this issue? .NET 6 is still supported until the end of next year, so it would be great if we could avoid unnecessary noise caused by issues such as these.

**Comment by deepchoudhery** [comment]
Hey,
Will address this in the next series of updates for sure.

Thanks,
Deep

**Comment by deepchoudhery** [comment]
Addressed, will be fixed in the servicing.
