### ISSUE TITLE
Unable to install the package from Nuget Package Manager

### ISSUE THREAD

**Issue by PiyushPayodhi** [dotnet/Scaffolding#2563]
I was trying to add Areas in my project for which I tried to install Microsoft.VisualStudio.Web.CodeGeneration.Design --version 8.0.0-rc.2.23509.1 both through Nuget Package Manager and through Console.

log  : Failed to download package 'Microsoft.VisualStudio.Web.CodeGeneration.Design.8.0.0-rc.2.23509.1' from 'https://api.nuget.org/v3-flatcontainer/microsoft.visualstudio.web.codegeneration.design/8.0.0-rc.2.23509.1/microsoft.visualstudio.web.codegeneration.design.8.0.0-rc.2.23509.1.nupkg'.
log  : An error occurred while sending the request.
log  :   Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
log  :   An existing connection was forcibly closed by the remote host.

Target framework: .NET 8.0
Operating system: Windows 11 Pro Version 10.0.22000 Build 22000
IDE: Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.8.0 Preview 1.0

**Comment by deepchoudhery** [comment]
Hmm this is less to do with the scaffolding package but with TLS and nuget, there seems to be many solutions online, refer to this[ one](https://learn.microsoft.com/en-us/answers/questions/959588/visual-studio-2022-wont-connect-to-nuget) for now please.
