### ISSUE TITLE
Need to upgrade Package Microsoft.VisualStudio.Web.CodeGeneration.Design

### ISSUE THREAD

**Issue by omarceloribeiro** [dotnet/Scaffolding#2583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Please this package need to be upgraded too. it is still in release candidate and is blocking a project MVC created in .Net 7 to be upgraded to .Net 8
https://www.nuget.org/packages/Microsoft.VisualStudio.Web.CodeGeneration.Design/

`
Error NU1107 Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 4.5.0 directly to project Project.Web.MVC to resolve this issue.

Project.Web.MVC -> Project.Infra.Data -> Microsoft.EntityFrameworkCore.Design 8.0.0 -> Microsoft.CodeAnalysis.CSharp.Workspaces 4.5.0 -> Microsoft.CodeAnalysis.Common (= 4.5.0)
Project.Web.MVC -> Microsoft.VisualStudio.Web.CodeGeneration.Design 7.0.11 > Microsoft.DotNet.Scaffolding.Shared 7.0.11 -> Microsoft.CodeAnalysis.CSharp.Features 4.4.0 -> Microsoft.CodeAnalysis.Common (= 4.4.0)
`
No workarounds.
The solution suggested in the error message didn't work

### Expected Behavior

build succeded.

### Steps To Reproduce

- Create MVC project in .Net 7
- Create other project for hold entity framework
- scaffold some views
- try to upgrade projects to .Net 8

### .NET Version

8.0.0

**Comment by deepchoudhery** [comment]
hmmm, I guess we don't really expect 8.0 dependencies in a .NET 7 app, I can fix this for CodeAnalysis to have a lowerbound instead of an exact version.
However, in the meantime, would you want to upgrade to 8.0.0-rc.2 version of `CodeGeneration.Design` and see if that resolves this issue. 

Thanks,
Deep

**Comment by omarceloribeiro** [comment]
**Solved setting this verison**
`
<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.0-rc.2.23509.1" />
`

**Comment by omarceloribeiro** [comment]
> hmmm, I guess we don't really expect 8.0 dependencies in a .NET 7 app, I can fix this for CodeAnalysis to have a lowerbound instead of an exact version. However, in the meantime, would you want to upgrade to 8.0.0-rc.2 version of `CodeGeneration.Design` and see if that resolves this issue.
> 
> Thanks, Deep

I had the idea to create a brand new project MVC to see how it would be working.
then I opened the references and found the solution. 
the new project is served like this: 

`
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.0-rc.2.23480.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.0-rc.2.23509.1" />
  </ItemGroup>
`

I believe they will upgrade it some day, but by now it is working.

**Comment by omarceloribeiro** [comment]
> I guess we don't really expect 8.0 dependencies in a .NET 7 app, I can fix this for CodeAnalysis to have a lowerbound instead of an exact version.

the .net 7 version is ok.
the problem appear when I change the version of my projects to .net 8 but left the version of Microsoft.VisualStudio.Web.CodeGeneration.Design in 7.0.11 (since still doesn't have the .net 8 version yet)
I dind'nt know that I could use the version 8.0.0-rc.2.23480.1 even with just the .net 8 version installed. so it worked. hope we get the .net 8 version of this package soon, so the config will not look ugly 😆

this is my enviroment:
`
dotnet --list-sdks
5.0.408 [C:\Program Files\dotnet\sdk]
8.0.100 [C:\Program Files\dotnet\sdk]
`

thank you

**Comment by omarceloribeiro** [comment]
by the way, I had created a copy of this issue in another repository, I was not aware it was the same place, sorry
please move to correct place or delete 
https://github.com/dotnet/core/issues/8916
thank you

**Comment by vlardn** [comment]
Please fix `Microsoft.EntityFrameworkCore.Design` too as it generates the same error:
```
ERROR NU1107	Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 4.8.0 directly to project TestProject to resolve this issue. 
 TestProject -> Microsoft.CodeAnalysis.CSharp 4.8.0 -> Microsoft.CodeAnalysis.Common (= 4.8.0) 
 TestProject -> Microsoft.EntityFrameworkCore.Design 8.0.0 -> Microsoft.CodeAnalysis.CSharp.Workspaces 4.5.0 -> Microsoft.CodeAnalysis.Common (= 4.5.0).
```
