### ISSUE TITLE
Nuget.ProjectModel version used in Microsoft.DotNet.Scaffolding.Shared has a high vulnerability

### ISSUE THREAD

**Issue by thompson-tomo** [dotnet/Scaffolding#2588]
### Describe the bug
All versions of the library are using a version of Nuget.ProjectModel which has an identified vulnerability which has been fixed in newer version of the library

### To reproduce
Open nuget package manager with library installed
Look at vulnerabilities of transitive packages and observe warning about vulnerability for Nuget.ProjectModel 
Look at dependencies of Microsoft.DotNet.Scaffolding.Shared and observe this is the source of the vulnerable library

### Expected behavior
Nuget.ProjectModel is upgraded to a version which doesn't contain vulnerability or dependency removed

### Further technical details
https://github.com/advisories/GHSA-6qmf-mmc7-6c2p

**Comment by thompson-tomo** [comment]
You are correct the affected package is a transitive dependency of many packages often many packages deep.

**Comment by mcurros2** [comment]
Any news on this? `Microsoft.VisualStudio.Web.CodeGeneration.Design` uses version 6.3.1, and 6.8.0 is available with no vulnerabilities. I think the references could be updated safely and repackage. A severe vulnerability will make us to uninstall this feature, and I don't know if it's possible.

Is there a workaround to update it manually?

**Comment by thompson-tomo** [comment]
@mcurros2 the workaround is to add the affected package as an explicit dependency which will update the transitive package.

**Comment by thompson-tomo** [comment]
6.8.0 is now being classified as impacted. Package should be updated to atleast 6.8.1

**Comment by tinohager** [comment]
Please push a new version of the package with the update of NuGet.* packages

**Comment by thompson-tomo** [comment]
Looks good, hence closing issue.
