### ISSUE TITLE
Microsoft.DotNet.Scaffolding.Shared 8.0.0 depends on prerelease version of Microsoft.CodeAnalysis.CSharp.Features

### ISSUE THREAD

**Issue by Mephistofeles** [dotnet/Scaffolding#2622]
Package Microsoft.DotNet.Scaffolding.Shared 8.0.0 depends on Microsoft.CodeAnalysis.CSharp.Features in version 4.8.0-3.final, which causes conflicts for example with Orleans 8.0:

```
Version conflict detected for Microsoft.CodeAnalysis.Common.
Microsoft.Orleans.Streaming 8.0.0 -> Microsoft.Orleans.Runtime 8.0.0 -> Microsoft.Orleans.Core 8.0.0 -> Microsoft.Orleans.Core.Abstractions 8.0.0 -> Microsoft.Orleans.Serialization 8.0.0 -> Microsoft.CodeAnalysis.Common (>= 4.8.0)
Microsoft.VisualStudio.Web.CodeGeneration.Design 8.0.0 -> Microsoft.DotNet.Scaffolding.Shared 8.0.0 -> Microsoft.CodeAnalysis.CSharp.Features 4.8.0-3.final -> Microsoft.CodeAnalysis.Common (= 4.8.0-3.final)
```

Microsoft.DotNet.Scaffolding.Shared version: 8.0.0
Target framework: .NET 8.0

**Comment by deepchoudhery** [comment]
fixed in v8.0.1, releasing next week (will close this then). Thanks.

**Comment by NotTsunami** [comment]
Doesn't appear to have made it into 8.0.1: https://github.com/dotnet/Scaffolding/blob/release/8.0/eng/Versions.props

**Comment by deepchoudhery** [comment]
The packages release for 8.0.1 include all the commits [here](https://github.com/dotnet/Scaffolding/commits/release/8.0/). The build for #2461 didn't pass due to a test issue which was subsequently fixed. Please try the scenario with the new 8.0.1 package and let me know thanks.

**Comment by deepchoudhery** [comment]
oops my bad, definitely thought I cherry-picked it from main.  I have a few more fixes I want to get in so will try to service this soon.

**Comment by NotTsunami** [comment]
Any chance of NuGetProjectModelVersion getting bumped for release/8.0 as well? Cheers.

**Comment by thompson-tomo** [comment]
@deepchoudhery for the nuget issue there is #2588 to cover that so would be good if both could be bumped at the same time

**Comment by deepchoudhery** [comment]
Yes will do @NotTsunami @thompson-tomo. Thanks for letting me know.

**Comment by NotTsunami** [comment]
Cheers, thanks so much! This and #2588 can be closed on next release.

**Comment by NotTsunami** [comment]
Microsoft.DotNet.Scaffolding.Shared 8.0.2 has [released](https://www.nuget.org/packages/Microsoft.VisualStudio.Web.CodeGeneration.Design/8.0.2) and this was fixed 🥳

**Comment by deepchoudhery** [comment]
Yes, ty for reporting issues. Closing.
