### ISSUE TITLE
Could not load file or assembly 'System.Composition.TypedParts, Version=1.0.31.0'

### ISSUE THREAD

**Issue by TontonTij** [dotnet/Scaffolding#484]
Hello,

I've created a layered ASP.NET Core Web Application (.Net Core) => target framework: .NetCoreApp 1.1, Which refers a business layer libraries .NetCoreApp 1.1 that uses the package '**System.Composition.TypedParts, Version = 1.0.31.0**, Culture = neutral, PublicKeyToken = b03f5f7f11d50a3a'.

When I run the application I have the error below:
FileLoadException: Could not load file or assembly 'System.Composition.TypedParts, Version=1.0.31.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040).

It's logic because in the ASP.NET Core Web Application project, the Microsoft.VisualStudio.Web.CodeGenerators.Mvc package loads the assembly **System.Composition.TypedParts version 1.0.27.0**
And I cannot update my business layer to load the version 1.0.27.0 because .NetCoreApp 1.1 cannot load this assembly.

I have already tried redirect assembly binding in config file but doesn't work. 
```
<dependentAssembly> 
<assemblyIdentity name="System.Composition.TypedParts" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" /> <bindingRedirect oldVersion="1.0.27.0" newVersion="1.0.31.0" /> 
</dependentAssembly>
```

Could you help me to solve this issue? 
Thank you

**Comment by prafullbhosale** [comment]
@TontonTij can you provide a sample repro project?

**Comment by TontonTij** [comment]
@prafullbhosale This is my repo project => [Sample](https://github.com/TontonTij/SampleProject)
Thanks

**Comment by prafullbhosale** [comment]
@TontonTij, I have tried to repro using the sample project above for the past couple of days, but I am not able to repro it locally. 

```
E:\git\SampleProject\Sample.Project.WebUI (master)
λ dotnet aspnet-codegenerator -p Sample.Project.WebUI.csproj controller --controllerName ManufacturersController --model Sample.Project.Core.Manufacturer --dataContext Sample.Project.WebUI.Data.CarContext --relativeFolderPath Controllers Command Line: -p Sample.Project.WebUI.csproj controller --controllerName ManufacturersController --model Sample.Project.Core.Manufacturer --dataContext Sample.Project.WebUI.Data.CarContext --relativeFolderPath Controllers
Microsoft (R) Build Engine version 15.3.117.23532
Copyright (C) Microsoft Corporation. All rights reserved.

  Sample.Project.Core -> E:\git\SampleProject\Sample.Project.Core\bin\Debug\netcoreapp1.1\Sample.Project.Core.dll
Building project ...
Microsoft (R) Build Engine version 15.3.117.23532
Copyright (C) Microsoft Corporation. All rights reserved.

  Sample.Project.Core -> E:\git\SampleProject\Sample.Project.Core\bin\Debug\netcoreapp1.1\Sample.Project.Core.dll
  Sample.Project.WebUI -> E:\git\SampleProject\Sample.Project.WebUI\bin\Debug\netcoreapp1.1\Sample.Project.WebUI.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:04.99
Command Line: --no-dispatch --port-number 58155 -p Sample.Project.WebUI.csproj controller --controllerName ManufacturersController --model Sample.Project.Core.Manufacturer --dataContext Sample.Project.WebUI.Data.CarContext --relativeFolderPath Controllers --dispatcher-version 1.0.0-rtm-10308
Finding the generator 'controller'...
Running the generator 'controller'...
Attempting to compile the application in memory with the modified DbContext
Attempting to figure out the EntityFramework metadata for the model and DbContext: Manufacturer
Added Controller : \Controllers\ManufacturersController.cs
Added View : \Views\Manufacturers\Create.cshtml
Added View : \Views\Manufacturers\Edit.cshtml
Added View : \Views\Manufacturers\Details.cshtml
Added View : \Views\Manufacturers\Delete.cshtml
Added View : \Views\Manufacturers\Index.cshtml
RunTime 00:00:14.71
```


Could you clear your local nuget cache, restore the projects and try again to see if that works? 
If that doesn't help, can you also provide the `project.assets.json` files from under the `obj` folders of both the projects?

**Comment by TontonTij** [comment]
@prafullbhosale, I cleared the nuget packages and I built the project to restore them on Visual Studio 2017 Enterprise.

```
Clearing NuGet HTTP cache: C:\Users\Tijani\AppData\Local\NuGet\v3-cache
Clearing NuGet cache: C:\Users\Tijani\AppData\Local\NuGet\Cache
Clearing NuGet global packages cache: C:\Users\Tijani\.nuget\packages\
Local resources cleared.
```
But I still have the exception at runtime.

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Composition.TypedParts, Version=1.0.31.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Composition.TypedParts, Version=1.0.31.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Sample.Project.Core.Container.MefInitialization()
   at Sample.Project.WebUI.Startup.ConfigureServices(IServiceCollection services) in D:\Visual Studio 2017\Sample.Project\Sample.Project.WebUI\Startup.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
.NET Core X64 v4.1.1.0    |   Microsoft.AspNetCore.Hosting version 1.1.1    |    Microsoft Windows 10.0.14393  
```
The attached zip contains the `project.assets.json` file that you requested.

[project.assets.zip](https://github.com/aspnet/Scaffolding/files/1009952/project.assets.zip)

**Comment by zaccharles** [comment]
@TontonTij Please try adding the same `System.Composition.TypedParts` reference to the `Sample.Project.WebUI` project.

**Comment by TontonTij** [comment]
@zaccharles I had already tested this bypass but it does not work. It works with you?

**Comment by zaccharles** [comment]
@TontonTij I came across your issue when trying to resolve my own. I don't have the exact problem, but it just seems like the host project doesn't know about System.Composition.TypedParts, or it has a binding redirect to an older version.

**Comment by TontonTij** [comment]
@zaccharles The package **Microsoft.VisualStudio.Web.CodeGenerators.Mvc** loads the assembly System.Composition.TypedParts version **1.0.27.0** and I had already tried a binding redirect to the version 1.0.31.0, but doesn't work like I explained in the issue. 
Thanks for your help

**Comment by prafullbhosale** [comment]
@TontonTij sorry for the delay here, I still haven't been able to pin point the issue. 
However, I have a potential workaround for you in the meantime. 
Can you try to add the below to your business layer library and then downgrade `System.Composition.TypedParts` to version 1.0.27? 

```xml
  <PropertyGroup>
    <PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8+wp8+wpa81;</PackageTargetFallback>
  </PropertyGroup>
```

**Comment by StingyJack** [comment]
This is broken in a new console app I have. As soon as I execute `var wks = MSBuildWorkspace.Create();`

So, not just Asp.net  =?

![image](https://user-images.githubusercontent.com/15381181/27778427-c1110e08-5f88-11e7-9b98-f2dc3086d81d.png)

**Comment by StingyJack** [comment]
This seems like a failure in MsBuild to detect needed dependencies ([here](https://stackoverflow.com/questions/15816769/dependent-dll-is-not-getting-copied-to-the-build-output-folder-in-visual-studio) or [here](https://stackoverflow.com/questions/1132243/msbuild-doesnt-copy-references-dll-files-if-using-project-dependencies-in-sol))

Its even surfaced as a [Mac-specific defect](https://github.com/Microsoft/msbuild/issues/1469)

There is no good reason for MsBuild to play "smart" like this. It just craps up the referencing project with needing all the other packages, or causes subtle bugs later on.

**Comment by mbedru** [comment]
i just visited https://www.nuget.org/packages/System.Composition.TypedParts/ 
and they i found the link to update  TypedParts in the nuget console using this link and it was the right answer for me=>>>
PM>
Install-Package System.Composition.TypedParts -Version 5.0.1

**Comment by deepchoudhery** [comment]
fixed for dotnet-scaffold, closing.
