### ISSUE TITLE
Remove dependency on Microsoft.DotNet.ProjectModel

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/Scaffolding#617]
This API was deprecated along with the rest of project.json, but this project still uses it in testing. We should remove or replace usages of this package.

**Comment by natemcmaster** [comment]
@prafullbhosale I took a look at this again. It looks like we have a bunch of disabled tests that haven't been re-enabled since the conversion from project.json to MSBuild. Is it okay to delete these tests altogether, or do you have plans to convert them to MSBuild?

**Comment by vijayrkn** [comment]
These are really old packages and no longer relevant. Closing.

**Comment by natemcmaster** [comment]
You might want to double check. Your code is still referencing this very old package 😉

**Comment by vijayrkn** [comment]
Oops sorry. Will have take a look.

**Comment by deepchoudhery** [comment]
removed https://github.com/dotnet/Scaffolding/pull/2944
