### ISSUE TITLE
Stop using DbContextOperations.CreateContext in EntityFrameworkModelProcessor

### ISSUE THREAD

**Issue by bricelam** [dotnet/Scaffolding#681]
It looks like the fix for #549 still needs to be applied to [src/VS.Web.CG.EFCore/EntityFrameworkModelProcessor.cs](https://github.com/aspnet/Scaffolding/blob/release/2.2/src/VS.Web.CG.EFCore/EntityFrameworkModelProcessor.cs)

**Comment by deepchoudhery** [comment]
fixed
