### ISSUE TITLE
Identity scaffolder should add a timestamp or guid to the database name

### ISSUE THREAD

**Issue by danroth27** [dotnet/Scaffolding#744]

**Comment by vijayrkn** [comment]
@HaoK  - This looks like an identity content issue. Can you take care of these?

**Comment by Rick-Anderson** [comment]
At least for 3.1 and later, the templates add a GUID to *appsettings.json*
@HaoK , can this be closed?

**Comment by HaoK** [comment]
Cool, thanks @Rick-Anderson
