### ISSUE TITLE
Can ASP.NET Identity 2.1 be made to use MVC UI not Web Pages?

### ISSUE THREAD

**Issue by blowdart** [dotnet/Scaffolding#864]
_From @A51UK on August 30, 2018 10:27_

I just try out the ASP.NET Identity 2.1, and was think of upgrade a project from Identity 2.0 to Identity 2.1 but found that it have been turn to the Web Pages Modal not the MVC one, is there a way to pick which ASP.NET Identity 2.1 UI modal to use (e.g. MVC not Web Pages)?  If not it would be a good think to added in the next update. 

_Copied from original issue: aspnet/Identity#1949_

**Comment by brockallen** [comment]
> There's been some discussion of giving two scaffold options

So options for either MVC or Razor Pages?

**Comment by A51UK** [comment]
Yes options for either MVC or Razor Pages would be great and would be very helpful but it would be best that by default the scaffold  would select the option base on the project template. Then allow the user to override the option.

**Comment by jhadz81** [comment]
I think its a bug that you select the MVC project template and you get Razor Page scaffolding.  This is causing me an insane amount of work when I have to rewrite the Razor scaffolding as MVC for Identity.

**Comment by TanvirArjel** [comment]
Any update about this please?

**Comment by blowdart** [comment]
No. Nothing yet. We're considering it for later versions, but have not made a decision.

**Comment by TanvirArjel** [comment]
@blowdart This is really frustrating! ASP.NET Core team have few very important miss-designed and this is one of them! :') Would be great if they fix it as soon as possible because almost every application requires identity..

**Comment by blowdart** [comment]
This is why we had a [survey](https://github.com/aspnet/Identity/issues/2058) on it, which will be followed up with customer calls to identify demand, then we'll see if the demand is there to schedule work in 3.0

**Comment by TanvirArjel** [comment]
@blowdart  I have submitted the survey. I think (may be most of the people will agree) best option would be:

**Generate identity as UI Razor class library only if the user select Razor Page template for the project and generate identity in MVC if user select MVC project template.**

**Comment by TanvirArjel** [comment]
@blowdart @danroth27   Any update about this major issue please!

**Comment by blowdart** [comment]
No.

**Comment by asafgo** [comment]
If I choose ASP.NET 2.2 Web Application (Model-View-Controller) template I expect to have AccountController and ManageController and not Razor Pages "Combine" with MVC.

Any updates when it will be available please?

**Comment by blowdart** [comment]
No.

When there is an update, either positive or negative I will update this issue.

**Comment by BloodyMettle** [comment]
> This is why we had a [survey](https://github.com/aspnet/Identity/issues/2058) on it, which will be followed up with customer calls to identify demand, then we'll see if the demand is there to schedule work in 3.0

Will there be any public visible summary of the survey? Would be nice to see what other people think.

**Comment by prince272** [comment]
I've rewritten the Asp Core Identity for Mvc. Feel free to take a look at https://github.com/prince272/AspCoreIdentityMvc

Simply change the url for the area 'Identity' to 'IdentityMvc' and you'll be automatically directed to the Mvc version for Identity.

**Comment by seancpeters** [comment]
@danroth27 @mkArtakMSFT

**Comment by Rick-Anderson** [comment]
@deepchoudhery  can you close this issue? 2.1 is out of support and it clutters up open issues.
