### ISSUE TITLE
Location of Built-In AspNet Core Web API Templates

### ISSUE THREAD

**Issue by tonysneed** [dotnet/Scaffolding#946]
Just wondering if it might be possible to customize the global AspNet Core C# web api templates? This is to answer a question posted on my repo: https://github.com/TrackableEntities/AspNetCore.ApiControllers.Templates/issues/6.

**Comment by seancpeters** [comment]
It's possible to replace the content files with your own content. But there's currently no good way to adjust the UI in conjunction with your changes - such as adding new user inputs.

The content is carried with the `microsoft.visualstudio.web.codegenerators.mvc` package, under the `Templates` folder. That project's .csproj file controls where the content files are placed, starting at about line 20:
https://github.com/aspnet/Scaffolding/blob/master/src/VS.Web.CG.Mvc/VS.Web.CG.Mvc.csproj

**Comment by neozhu** [comment]
There is currently no way to add custom parameters with scaffolding UI or new features（class，service） to the template. ？？

**Comment by seancpeters** [comment]
@tonysneed - If you modify the scaffolding content in your installed Microsoft.VisualStudio.Web.CodeGenerators.Mvc package, then that modified content should be used when scaffolding through Visual Studio. When scaffolding, Visual Studio uses Microsoft.VisualStudio.Web.CodeGenerators.Mvc to create the generated content.

**Comment by seancpeters** [comment]
@neozhu - what you said is correct. With an existing scaffolder, you can only modify the generated content, but not the configuration parameters that Visual Studio asks the user to supply.
