### ISSUE TITLE
Scaffolding should not list individual files per each dependency rather depend on folders

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/Scaffolding#957]
Currently in Scaffolding `VS.Web.CG.Mvc\Identity\bootstrap4_identitygeneratorfilesconfig.json` lists all the individual files for dependencies (like Bootstrap) to be copied to the `wwwroot` folder. This model results in scaffolding breaks when the list of files changes with dependency updates.

### Solution
A way to avoid these type of issues the engine can be updated to actual allow dependency folders to be listed instead, so all the files with that folder will be copied to the final directory.

**Comment by deepchoudhery** [comment]
fixed for dotnet-scaffold, closing., please use the new 'dotnet-scaffold' tool. Blog [here](https://devblogs.microsoft.com/dotnet/introducing-dotnet-scaffold/)
