### ISSUE TITLE
ASP.NET Core API controller scaffolder and item template issues

### ISSUE THREAD

**Issue by danroth27** [dotnet/Scaffolding#967]
There are numerous issues with the API controller scaffolder and item template:
- Derive from `ControllerBase`, not `Controller`
- Return `ActionResult<T>` from actions where appropriate
- Typo in comment on the generated delete action - doesn't match the controller name
- Inconsistent colons after verbs in comments

@glennc @seancpeters

**Comment by vijayrkn** [comment]
@mkArtakMSFT - These are all content issues. Do you want to handle this?

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg assigning this to you to handle for the 5.0-preview1 release.

**Comment by vijayrkn** [comment]
Both Api Controller Scaffolder and item template point to the same source starting 16.6 

Here are the contents: 

Empty Api Controller: 
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication38
{
    [Route("api/[controller]")]
    [ApiController]
    public class ValuesController1 : ControllerBase
    {
    }
}
```

Api Controller with read/write actions:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace WebApplication38
{
    [Route("api/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {
        // GET: api/<ValuesController>
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/<ValuesController>/5
        [HttpGet("{id}")]
        public string Get(int id)
        {
            return "value";
        }

        // POST api/<ValuesController>
        [HttpPost]
        public void Post([FromBody] string value)
        {
        }

        // PUT api/<ValuesController>/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody] string value)
        {
        }

        // DELETE api/<ValuesController>/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}
```

@danroth27 - Can you please confirm what improvements would you like to see in the 2 files above? 

Adding @phenning & @deepchoudhery to get the files updated once we finalize on the content.

**Comment by danroth27** [comment]
I believe this issue can be closed. I checked the code of the API controller scaffolder with EF Core, which I believe is what originally motivated this issue, and it no longer has any of the problems listed in this issue report.
