### ISSUE TITLE
Razor pages scaffold ignores RootNamespace set via csproj file

### ISSUE THREAD

**Issue by nphmuller** [dotnet/Scaffolding#968]
## Steps to reproduce:
- `dotnet new webapp --name ScaffoldIncorrectNamespace`
- Open ScaffoldIncorrectNamespace.csproj
  - Add `<RootNamespace>Overridden.Namespace</RootNamespace>`
  - Add `<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.3" PrivateAssets="All" />`
- Open project in Visual Studio (tested in 15.9.8 and 15.9.9)
- In Solution Explorer: 
  - Right click Pages folder
  - Add -> Razor Page...
  - Make sure `Generate PageModel class` is checked
- Open the newly scaffolded model (.cshtml.cs)

## Expected behavior:
The newly scaffolded .cshtml.cs file should have a namespace of `Overridden.Namespace.Pages`

## Actual behavior:
The namespace is `ScaffoldIncorrectNamespace.Pages`

### Target framework(s):
netcoreapp2.2

### Package version of Microsoft.AspNetCore.App or Microsoft.AspNetCore.All (if applicable):
No version specified. Latest installed runtime is 2.2.2

### Package version of Microsoft.VisualStudio.Web.CodeGeneration.Design - this may be added to your project by scaffolding:
2.2.3

**Comment by vijayrkn** [comment]
@deepchoudhery - I remember you mentioned about this. Is this fixed?

**Comment by deepchoudhery** [comment]
Yes this is fixed for VS 16.4.6 and onwards. Let me know if you still run into the issue.
